// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class CatChipComponentHandle extends ffai.ProjectComponentHandle<CatChipParams, CatChipState> {
  CatChipComponentHandle()
    : super(
        name: "CatChip",
        key: "Container_y6n7q2rs",
        params: const CatChipParams(),
        state: const CatChipState(),
        widgets: CatChipWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "active": ffai.bool_,
          "label": ffai.string,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? active = ffai.kUnsetComponentArg,
    Object? label = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(active)) "active": active,
        if (!ffai.isUnsetComponentArg(label)) "label": label,
      },
    );
  }
}

final class CatChipParams {
  const CatChipParams();
  ffai.ProjectParamHandle get active =>
      const ffai.ProjectParamHandle(
        name: "active",
        key: "8el760w5",
        typeName: "Boolean",
      );
  ffai.ProjectParamHandle get label =>
      const ffai.ProjectParamHandle(
        name: "label",
        key: "2gevpmm9",
        typeName: "String",
      );
}

final class CatChipState {
  const CatChipState();
}

abstract final class CatChipWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_y6n7q2rs",
      type: "Container",
      path: "CatChip",
      name: "CatChip",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Column_l22tlcie",
          type: "Column",
          path: "CatChip.children[0]",
          name: "Column",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Container_l4ut05li",
              type: "Container",
              path: "CatChip.children[0].children[0]",
              name: "Container",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_q1ae4dkp",
                  type: "Text",
                  path: "CatChip.children[0].children[0].children[0]",
                  name: "Text",
                ),
              ],
            ),
            ffai.ProjectWidgetHandle(
              key: "Container_lmuiy4yt",
              type: "Container",
              path: "CatChip.children[0].children[1]",
              name: "Container",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_9fnt040e",
                  type: "Text",
                  path: "CatChip.children[0].children[1].children[0]",
                  name: "Text",
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

