// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class PinSheetComponentHandle extends ffai.ProjectComponentHandle<PinSheetParams, PinSheetState> {
  PinSheetComponentHandle()
    : super(
        name: "PinSheet",
        key: "Container_zq033rak",
        params: const PinSheetParams(),
        state: const PinSheetState(),
        widgets: PinSheetWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "onDone": ffai.json,
          "startPin": ffai.string,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? onDone = ffai.kUnsetComponentArg,
    Object? startPin = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(onDone)) "onDone": onDone,
        if (!ffai.isUnsetComponentArg(startPin)) "startPin": startPin,
      },
    );
  }
}

final class PinSheetParams {
  const PinSheetParams();
  ffai.ProjectParamHandle get onDone =>
      const ffai.ProjectParamHandle(
        name: "onDone",
        key: "57td2u8p",
        typeName: "Action",
      );
  ffai.ProjectParamHandle get startPin =>
      const ffai.ProjectParamHandle(
        name: "startPin",
        key: "d7hbj6ka",
        typeName: "String",
      );
}

final class PinSheetState {
  const PinSheetState();
}

abstract final class PinSheetWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_zq033rak",
      type: "Container",
      path: "PinSheet",
      name: "PinSheet",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Container_icgnajdp",
          type: "Container",
          path: "PinSheet.children[0]",
          name: "Container",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Column_znowezvv",
              type: "Column",
              path: "PinSheet.children[0].children[0]",
              name: "Column",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Container_4s5s0kan",
                  type: "Container",
                  path: "PinSheet.children[0].children[0].children[0]",
                  name: "Container",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Row_jls6518q",
                      type: "Row",
                      path: "PinSheet.children[0].children[0].children[0].children[0]",
                      name: "Row",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Text_bobq6lzg",
                          type: "Text",
                          path: "PinSheet.children[0].children[0].children[0].children[0].children[0]",
                          name: "pinSheetTitle",
                          text: "Pin your location",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Container_5msrfwjs",
                          type: "Container",
                          path: "PinSheet.children[0].children[0].children[0].children[0].children[1]",
                          name: "pinCancel",
                          triggers: const <String>[
                            "ON_TAP",
                          ],
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Text_dvve5pio",
                              type: "Text",
                              path: "PinSheet.children[0].children[0].children[0].children[0].children[1].children[0]",
                              name: "Text",
                              text: "Cancel",
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_et5qpxvm",
                  type: "Container",
                  path: "PinSheet.children[0].children[0].children[1]",
                  name: "pinSheetMap",
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_oesjdk9b",
                  type: "Container",
                  path: "PinSheet.children[0].children[0].children[2]",
                  name: "Container",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_ps2jptez",
                      type: "Column",
                      path: "PinSheet.children[0].children[0].children[2].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Text_16nahxcw",
                          type: "Text",
                          path: "PinSheet.children[0].children[0].children[2].children[0].children[0]",
                          name: "pinSheetHint",
                          text: "Drag the map to move the pin",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_erqqg1rm",
                          type: "Text",
                          path: "PinSheet.children[0].children[0].children[2].children[0].children[1]",
                          name: "pinSheetSearching",
                          text: "Finding address...",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_jnoram3a",
                          type: "Text",
                          path: "PinSheet.children[0].children[0].children[2].children[0].children[2]",
                          name: "pinSheetAddress",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_y9yiup39",
                          type: "Text",
                          path: "PinSheet.children[0].children[0].children[2].children[0].children[3]",
                          name: "pinSheetCoords",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Button_6vpby2te",
                          type: "Button",
                          path: "PinSheet.children[0].children[0].children[2].children[0].children[4]",
                          name: "pinConfirm",
                          text: "Use this location",
                          triggers: const <String>[
                            "ON_TAP",
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

