// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class ShoeCardComponentHandle extends ffai.ProjectComponentHandle<ShoeCardParams, ShoeCardState> {
  ShoeCardComponentHandle()
    : super(
        name: "ShoeCard",
        key: "Container_nxk8vohg",
        params: const ShoeCardParams(),
        state: const ShoeCardState(),
        widgets: ShoeCardWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "badge": ffai.string,
          "imageUrl": ffai.string,
          "priceLabel": ffai.string,
          "sub": ffai.string,
          "title": ffai.string,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? badge = ffai.kUnsetComponentArg,
    Object? imageUrl = ffai.kUnsetComponentArg,
    Object? priceLabel = ffai.kUnsetComponentArg,
    Object? sub = ffai.kUnsetComponentArg,
    Object? title = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(badge)) "badge": badge,
        if (!ffai.isUnsetComponentArg(imageUrl)) "imageUrl": imageUrl,
        if (!ffai.isUnsetComponentArg(priceLabel)) "priceLabel": priceLabel,
        if (!ffai.isUnsetComponentArg(sub)) "sub": sub,
        if (!ffai.isUnsetComponentArg(title)) "title": title,
      },
    );
  }
}

final class ShoeCardParams {
  const ShoeCardParams();
  ffai.ProjectParamHandle get badge =>
      const ffai.ProjectParamHandle(
        name: "badge",
        key: "h6tn2mgl",
        typeName: "String",
      );
  ffai.ProjectParamHandle get imageUrl =>
      const ffai.ProjectParamHandle(
        name: "imageUrl",
        key: "ec9obyi3",
        typeName: "String",
      );
  ffai.ProjectParamHandle get priceLabel =>
      const ffai.ProjectParamHandle(
        name: "priceLabel",
        key: "xpdh59fk",
        typeName: "String",
      );
  ffai.ProjectParamHandle get sub =>
      const ffai.ProjectParamHandle(
        name: "sub",
        key: "mre35s7m",
        typeName: "String",
      );
  ffai.ProjectParamHandle get title =>
      const ffai.ProjectParamHandle(
        name: "title",
        key: "v8dgineh",
        typeName: "String",
      );
}

final class ShoeCardState {
  const ShoeCardState();
}

abstract final class ShoeCardWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_nxk8vohg",
      type: "Container",
      path: "ShoeCard",
      name: "ShoeCard",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Container_p17zn052",
          type: "Container",
          path: "ShoeCard.children[0]",
          name: "Container",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Column_csulo67w",
              type: "Column",
              path: "ShoeCard.children[0].children[0]",
              name: "Column",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Image_z9p2xqg7",
                  type: "Image",
                  path: "ShoeCard.children[0].children[0].children[0]",
                  name: "Image",
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_5rgwxeyu",
                  type: "Container",
                  path: "ShoeCard.children[0].children[0].children[1]",
                  name: "Container",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_705b0obw",
                      type: "Column",
                      path: "ShoeCard.children[0].children[0].children[1].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Container_ucyen0lm",
                          type: "Container",
                          path: "ShoeCard.children[0].children[0].children[1].children[0].children[0]",
                          name: "Container",
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Text_cx9b9zq7",
                              type: "Text",
                              path: "ShoeCard.children[0].children[0].children[1].children[0].children[0].children[0]",
                              name: "Text",
                            ),
                          ],
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_g70nwyob",
                          type: "Text",
                          path: "ShoeCard.children[0].children[0].children[1].children[0].children[1]",
                          name: "Text",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_4xy0b8zk",
                          type: "Text",
                          path: "ShoeCard.children[0].children[0].children[1].children[0].children[2]",
                          name: "Text",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Text_4z5ux1mq",
                          type: "Text",
                          path: "ShoeCard.children[0].children[0].children[1].children[0].children[3]",
                          name: "Text",
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

