// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class ProductCardComponentHandle extends ffai.ProjectComponentHandle<ProductCardParams, ProductCardState> {
  ProductCardComponentHandle()
    : super(
        name: "ProductCard",
        key: "Container_4jukr0hd",
        params: const ProductCardParams(),
        state: const ProductCardState(),
        widgets: ProductCardWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "badge": ffai.string,
          "image": ffai.string,
          "onTapAction": ffai.json,
          "price": ffai.double_,
          "productName": ffai.string,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? badge = ffai.kUnsetComponentArg,
    Object? image = ffai.kUnsetComponentArg,
    Object? onTapAction = ffai.kUnsetComponentArg,
    Object? price = ffai.kUnsetComponentArg,
    Object? productName = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(badge)) "badge": badge,
        if (!ffai.isUnsetComponentArg(image)) "image": image,
        if (!ffai.isUnsetComponentArg(onTapAction)) "onTapAction": onTapAction,
        if (!ffai.isUnsetComponentArg(price)) "price": price,
        if (!ffai.isUnsetComponentArg(productName)) "productName": productName,
      },
    );
  }
}

final class ProductCardParams {
  const ProductCardParams();
  ffai.ProjectParamHandle get badge =>
      const ffai.ProjectParamHandle(
        name: "badge",
        key: "a8o6iq6m",
        typeName: "String",
      );
  ffai.ProjectParamHandle get image =>
      const ffai.ProjectParamHandle(
        name: "image",
        key: "purulagk",
        typeName: "String",
      );
  ffai.ProjectParamHandle get onTapAction =>
      const ffai.ProjectParamHandle(
        name: "onTapAction",
        key: "0vwjvr52",
        typeName: "Action",
      );
  ffai.ProjectParamHandle get price =>
      const ffai.ProjectParamHandle(
        name: "price",
        key: "wlkbpymv",
        typeName: "Double",
      );
  ffai.ProjectParamHandle get productName =>
      const ffai.ProjectParamHandle(
        name: "productName",
        key: "918k7igj",
        typeName: "String",
      );
}

final class ProductCardState {
  const ProductCardState();
}

abstract final class ProductCardWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_4jukr0hd",
      type: "Container",
      path: "ProductCard",
      name: "ProductCard",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Container_6nczuljk",
          type: "Container",
          path: "ProductCard.children[0]",
          name: "Container",
          triggers: const <String>[
            "ON_TAP",
          ],
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Column_u37fcj7q",
              type: "Column",
              path: "ProductCard.children[0].children[0]",
              name: "Column",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Stack_uio488w3",
                  type: "Stack",
                  path: "ProductCard.children[0].children[0].children[0]",
                  name: "Stack",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Image_kqr1idqq",
                      type: "Image",
                      path: "ProductCard.children[0].children[0].children[0].children[0]",
                      name: "Image",
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "Container_om7bze9q",
                      type: "Container",
                      path: "ProductCard.children[0].children[0].children[0].children[1]",
                      name: "Container Margin",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Container_myw8hwng",
                          type: "Container",
                          path: "ProductCard.children[0].children[0].children[0].children[1].children[0]",
                          name: "Container",
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Text_pkcvknvm",
                              type: "Text",
                              path: "ProductCard.children[0].children[0].children[0].children[1].children[0].children[0]",
                              name: "Text",
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_wi6xj5a6",
                  type: "Container",
                  path: "ProductCard.children[0].children[0].children[1]",
                  name: "Container",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Column_tp4xgk8o",
                      type: "Column",
                      path: "ProductCard.children[0].children[0].children[1].children[0]",
                      name: "Column",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Text_fjl081nq",
                          type: "Text",
                          path: "ProductCard.children[0].children[0].children[1].children[0].children[0]",
                          name: "Text",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Row_dfhjphs2",
                          type: "Row",
                          path: "ProductCard.children[0].children[0].children[1].children[0].children[1]",
                          name: "Row",
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Text_i77okwj8",
                              type: "Text",
                              path: "ProductCard.children[0].children[0].children[1].children[0].children[1].children[0]",
                              name: "Text",
                              text: "₱",
                            ),
                            ffai.ProjectWidgetHandle(
                              key: "Text_oke8dwne",
                              type: "Text",
                              path: "ProductCard.children[0].children[0].children[1].children[0].children[1].children[1]",
                              name: "Text",
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

