// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

abstract final class AppState {
  static const authToken = ffai.ProjectAppStateFieldHandle(
    name: "authToken",
    key: "z0k922rm",
    typeName: "String",
    persisted: true,
  );
  static const bag = ffai.ProjectAppStateFieldHandle(
    name: "bag",
    key: "0r7tvkyh",
    typeName: "List<DataStruct<BagItem>>",
    persisted: true,
  );
  static const isAdmin = ffai.ProjectAppStateFieldHandle(
    name: "isAdmin",
    key: "goe4ps2x",
    typeName: "Boolean",
    persisted: true,
  );
  static const lastOrderId = ffai.ProjectAppStateFieldHandle(
    name: "lastOrderId",
    key: "08z93uqn",
    typeName: "Integer",
    persisted: true,
  );
  static const signedIn = ffai.ProjectAppStateFieldHandle(
    name: "signedIn",
    key: "w9gopo6y",
    typeName: "Boolean",
    persisted: true,
  );
  static const userAddress = ffai.ProjectAppStateFieldHandle(
    name: "userAddress",
    key: "tk51564r",
    typeName: "String",
    persisted: true,
  );
  static const userEmail = ffai.ProjectAppStateFieldHandle(
    name: "userEmail",
    key: "urkcaaix",
    typeName: "String",
    persisted: true,
  );
  static const userFullName = ffai.ProjectAppStateFieldHandle(
    name: "userFullName",
    key: "fvgq075j",
    typeName: "String",
    persisted: true,
  );
  static const userId = ffai.ProjectAppStateFieldHandle(
    name: "userId",
    key: "rtyhhjac",
    typeName: "Integer",
    persisted: true,
  );
  static const userPhone = ffai.ProjectAppStateFieldHandle(
    name: "userPhone",
    key: "rtiabpbb",
    typeName: "String",
    persisted: true,
  );
  static const userRole = ffai.ProjectAppStateFieldHandle(
    name: "userRole",
    key: "dad4gs9z",
    typeName: "String",
    persisted: true,
  );
  static const username = ffai.ProjectAppStateFieldHandle(
    name: "username",
    key: "2dlbvuuj",
    typeName: "String",
    persisted: true,
  );
  static const all = <ffai.ProjectAppStateFieldHandle>[
    authToken,
    bag,
    isAdmin,
    lastOrderId,
    signedIn,
    userAddress,
    userEmail,
    userFullName,
    userId,
    userPhone,
    userRole,
    username,
  ];
}

