// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;
import 'components/cat_chip.dart' show CatChipComponentHandle;
import 'components/shoe_card.dart' show ShoeCardComponentHandle;

abstract final class Components {
  static final catChip = CatChipComponentHandle();
  static final shoeCard = ShoeCardComponentHandle();
  static final all = <ffai.ProjectComponentHandle>[
    catChip,
    shoeCard,
  ];
}
