// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;
import 'pages/account.dart' show accountHandle;
import 'pages/addresses.dart' show addressesHandle;
import 'pages/bag.dart' show bagHandle;
import 'pages/checkout.dart' show checkoutHandle;
import 'pages/confirmed.dart' show confirmedHandle;
import 'pages/help.dart' show helpHandle;
import 'pages/info_page.dart' show infoPageHandle;
import 'pages/my_orders.dart' show myOrdersHandle;
import 'pages/notifications.dart' show notificationsHandle;
import 'pages/order_detail.dart' show orderDetailHandle;
import 'pages/payment.dart' show paymentHandle;
import 'pages/profile.dart' show profileHandle;
import 'pages/register.dart' show registerHandle;
import 'pages/reviews.dart' show reviewsHandle;
import 'pages/shoe_details.dart' show shoeDetailsHandle;
import 'pages/shop.dart' show shopHandle;
import 'pages/sign_in.dart' show signInHandle;
import 'pages/wishlist.dart' show wishlistHandle;

abstract final class Pages {
  static final account = accountHandle;
  static final addresses = addressesHandle;
  static final bag = bagHandle;
  static final checkout = checkoutHandle;
  static final confirmed = confirmedHandle;
  static final help = helpHandle;
  static final infoPage = infoPageHandle;
  static final myOrders = myOrdersHandle;
  static final notifications = notificationsHandle;
  static final orderDetail = orderDetailHandle;
  static final payment = paymentHandle;
  static final profile = profileHandle;
  static final register = registerHandle;
  static final reviews = reviewsHandle;
  static final shoeDetails = shoeDetailsHandle;
  static final shop = shopHandle;
  static final signIn = signInHandle;
  static final wishlist = wishlistHandle;
  static final all = <ffai.ProjectPageHandle>[
    account,
    addresses,
    bag,
    checkout,
    confirmed,
    help,
    infoPage,
    myOrders,
    notifications,
    orderDetail,
    payment,
    profile,
    register,
    reviews,
    shoeDetails,
    shop,
    signIn,
    wishlist,
  ];
}
