// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'dart:collection';

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

abstract final class Enums {
  static const all = <ffai.EnumHandle>[];
}

abstract final class Structs {
  static final ffai.StructHandle addressList = ffai.StructHandle(
    "AddressList",
    <String, ffai.DslType>{
      "count": ffai.int_,
      "items": ffai.listOf(Structs.addressRow),
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle addressRow = ffai.StructHandle(
    "AddressRow",
    <String, ffai.DslType>{
      "address": ffai.string,
      "id": ffai.int_,
      "is_default": ffai.bool_,
      "label": ffai.string,
      "latitude": ffai.string,
      "longitude": ffai.string,
      "map_url": ffai.string,
      "phone": ffai.string,
      "recipient_name": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle apiMessage = ffai.StructHandle(
    "ApiMessage",
    <String, ffai.DslType>{
      "message": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle apiNote = ffai.StructHandle(
    "ApiNote",
    <String, ffai.DslType>{
      "message": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle authResponse = ffai.StructHandle(
    "AuthResponse",
    <String, ffai.DslType>{
      "expires_at": ffai.string,
      "token": ffai.string,
      "user": Structs.authUser,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle authUser = ffai.StructHandle(
    "AuthUser",
    <String, ffai.DslType>{
      "address": ffai.string,
      "email": ffai.string,
      "full_name": ffai.string,
      "id": ffai.int_,
      "is_admin": ffai.bool_,
      "phone": ffai.string,
      "role": ffai.string,
      "username": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle bagItem = ffai.StructHandle(
    "BagItem",
    <String, ffai.DslType>{
      "id": ffai.int_,
      "image": ffai.string,
      "name": ffai.string,
      "price": ffai.double_,
      "qty": ffai.int_,
      "size": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle cartResponse = ffai.StructHandle(
    "CartResponse",
    <String, ffai.DslType>{
      "count": ffai.int_,
      "items": ffai.listOf(Structs.bagItem),
      "shipping": ffai.double_,
      "subtotal": ffai.double_,
      "total": ffai.double_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle catalogResponse = ffai.StructHandle(
    "CatalogResponse",
    <String, ffai.DslType>{
      "count": ffai.int_,
      "products": ffai.listOf(Structs.shoe),
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle deviceRegistered = ffai.StructHandle(
    "DeviceRegistered",
    <String, ffai.DslType>{
      "registered": ffai.bool_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle infoMenu = ffai.StructHandle(
    "InfoMenu",
    <String, ffai.DslType>{
      "count": ffai.int_,
      "items": ffai.listOf(Structs.infoPageRow),
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle infoPage = ffai.StructHandle(
    "InfoPage",
    <String, ffai.DslType>{
      "content": ffai.string,
      "slug": ffai.string,
      "title": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle infoPageRow = ffai.StructHandle(
    "InfoPageRow",
    <String, ffai.DslType>{
      "slug": ffai.string,
      "title": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle myOrdersResponse = ffai.StructHandle(
    "MyOrdersResponse",
    <String, ffai.DslType>{
      "count": ffai.int_,
      "orders": ffai.listOf(Structs.orderRow),
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle notificationList = ffai.StructHandle(
    "NotificationList",
    <String, ffai.DslType>{
      "count": ffai.int_,
      "items": ffai.listOf(Structs.notificationRow),
      "unread": ffai.int_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle notificationRow = ffai.StructHandle(
    "NotificationRow",
    <String, ffai.DslType>{
      "created_at": ffai.string,
      "id": ffai.int_,
      "is_read": ffai.bool_,
      "message": ffai.string,
      "title": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle orderCreated = ffai.StructHandle(
    "OrderCreated",
    <String, ffai.DslType>{
      "checkout_url": ffai.string,
      "id": ffai.int_,
      "message": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle orderEvent = ffai.StructHandle(
    "OrderEvent",
    <String, ffai.DslType>{
      "created_at": ffai.string,
      "note": ffai.string,
      "status": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle orderFull = ffai.StructHandle(
    "OrderFull",
    <String, ffai.DslType>{
      "created_at": ffai.string,
      "customer_address": ffai.string,
      "customer_name": ffai.string,
      "customer_phone": ffai.string,
      "id": ffai.int_,
      "items": ffai.listOf(Structs.orderLine),
      "payment_method": ffai.string,
      "payment_status": ffai.string,
      "status": ffai.string,
      "status_history": ffai.listOf(Structs.orderEvent),
      "total_amount": ffai.string,
      "tracking_number": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle orderLine = ffai.StructHandle(
    "OrderLine",
    <String, ffai.DslType>{
      "product_name": ffai.string,
      "quantity": ffai.int_,
      "size": ffai.string,
      "subtotal": ffai.string,
      "unit_price": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle orderRow = ffai.StructHandle(
    "OrderRow",
    <String, ffai.DslType>{
      "created_at": ffai.string,
      "customer_address": ffai.string,
      "customer_email": ffai.string,
      "customer_name": ffai.string,
      "customer_phone": ffai.string,
      "id": ffai.int_,
      "payment_method": ffai.string,
      "payment_status": ffai.string,
      "status": ffai.string,
      "total_amount": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle profile = ffai.StructHandle(
    "Profile",
    <String, ffai.DslType>{
      "address": ffai.string,
      "email": ffai.string,
      "full_name": ffai.string,
      "id": ffai.int_,
      "phone": ffai.string,
      "role": ffai.string,
      "username": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle profileSaved = ffai.StructHandle(
    "ProfileSaved",
    <String, ffai.DslType>{
      "message": ffai.string,
      "profile": Structs.profile,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle reviewFeed = ffai.StructHandle(
    "ReviewFeed",
    <String, ffai.DslType>{
      "average": ffai.double_,
      "can_review": ffai.bool_,
      "count": ffai.int_,
      "has_purchased": ffai.bool_,
      "has_reviewed": ffai.bool_,
      "items": ffai.listOf(Structs.reviewRow),
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle reviewRow = ffai.StructHandle(
    "ReviewRow",
    <String, ffai.DslType>{
      "comment": ffai.string,
      "created_at": ffai.string,
      "id": ffai.int_,
      "rating": ffai.int_,
      "username": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle sessionCheck = ffai.StructHandle(
    "SessionCheck",
    <String, ffai.DslType>{
      "valid": ffai.bool_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle shoe = ffai.StructHandle(
    "Shoe",
    <String, ffai.DslType>{
      "available_sizes": ffai.listOf(ffai.string),
      "badge": ffai.string,
      "category": ffai.string,
      "description": ffai.string,
      "id": ffai.int_,
      "image": ffai.string,
      "name": ffai.string,
      "price": ffai.string,
      "sale_price": ffai.string,
      "stock": ffai.int_,
      "subcategory": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle storeSettings = ffai.StructHandle(
    "StoreSettings",
    <String, ffai.DslType>{
      "card": ffai.bool_,
      "categories": ffai.listOf(ffai.string),
      "cod": ffai.bool_,
      "gcash": ffai.bool_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle taxonomyList = ffai.StructHandle(
    "TaxonomyList",
    <String, ffai.DslType>{
      "count": ffai.int_,
      "items": ffai.listOf(Structs.taxonomyRow),
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle taxonomyRow = ffai.StructHandle(
    "TaxonomyRow",
    <String, ffai.DslType>{
      "category": ffai.string,
      "subcategory": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle wishlist = ffai.StructHandle(
    "Wishlist",
    <String, ffai.DslType>{
      "count": ffai.int_,
      "items": ffai.listOf(Structs.shoe),
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle wishlistFlag = ffai.StructHandle(
    "WishlistFlag",
    <String, ffai.DslType>{
      "wishlisted": ffai.bool_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle wishlistToggled = ffai.StructHandle(
    "WishlistToggled",
    <String, ffai.DslType>{
      "count": ffai.int_,
      "items": ffai.listOf(Structs.shoe),
      "wishlisted": ffai.bool_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final all = <ffai.StructHandle>[
    addressList,
    addressRow,
    apiMessage,
    apiNote,
    authResponse,
    authUser,
    bagItem,
    cartResponse,
    catalogResponse,
    deviceRegistered,
    infoMenu,
    infoPage,
    infoPageRow,
    myOrdersResponse,
    notificationList,
    notificationRow,
    orderCreated,
    orderEvent,
    orderFull,
    orderLine,
    orderRow,
    profile,
    profileSaved,
    reviewFeed,
    reviewRow,
    sessionCheck,
    shoe,
    storeSettings,
    taxonomyList,
    taxonomyRow,
    wishlist,
    wishlistFlag,
    wishlistToggled,
  ];
}

abstract final class Collections {
  static const all = <ffai.ProjectCollectionHandle>[];
}

abstract final class Tables {
  static const all = <ffai.ProjectTableHandle>[];
}

abstract final class CustomCode {
  static const functions = <String>[
    "activePrice",
    "badgeOf",
    "bagBlocker",
    "bagCount",
    "bagSubtotal",
    "bagTotal",
    "bumpQty",
    "cartLines",
    "countText",
    "hasNoAddresses",
    "hasSale",
    "imgUrl",
    "joinPin",
    "listStillHas",
    "orderHeadline",
    "orderItems",
    "orderSubline",
    "peso",
    "pesoN",
    "pinPart",
    "sizeSellable",
    "subcategoriesOf",
    "textOr",
    "titleCase",
    "toNum",
    "urlSafe",
  ];
  static const actions = <String>[
    "currentPin",
    "deviceToken",
  ];
  static const widgets = <String>[
    "PinMap",
  ];
}

