[mcp_servers.flutterflow_ai]
command = "C:\\Users\\jbbal\\flutter\\bin\\cache\\dart-sdk\\bin\\dart.exe"
args = ["C:\\Users\\jbbal\\OneDrive\\Desktop\\flutter workspace\\solecraftfinal\\.flutterflow/sdk/flutterflow_ai\\mcp\\server.dill", "--dir", "C:\\Users\\jbbal\\OneDrive\\Desktop\\flutter workspace\\solecraftfinal"]
