// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

abstract final class AppState {
  static const authToken = ffai.ProjectAppStateFieldHandle(
    name: "authToken",
    key: "c2gwqiaw",
    typeName: "String",
    persisted: true,
  );
  static const cartItems = ffai.ProjectAppStateFieldHandle(
    name: "cartItems",
    key: "f1odx1d3",
    typeName: "List<DataStruct<CartItem>>",
    persisted: true,
  );
  static const isLoggedIn = ffai.ProjectAppStateFieldHandle(
    name: "isLoggedIn",
    key: "pfcp12p5",
    typeName: "Boolean",
    persisted: true,
  );
  static const userAddress = ffai.ProjectAppStateFieldHandle(
    name: "userAddress",
    key: "v6ztwif8",
    typeName: "String",
    persisted: true,
  );
  static const userEmail = ffai.ProjectAppStateFieldHandle(
    name: "userEmail",
    key: "913vpvav",
    typeName: "String",
    persisted: true,
  );
  static const userId = ffai.ProjectAppStateFieldHandle(
    name: "userId",
    key: "9b1fmj1i",
    typeName: "Integer",
    persisted: true,
  );
  static const userName = ffai.ProjectAppStateFieldHandle(
    name: "userName",
    key: "wnipka8r",
    typeName: "String",
    persisted: true,
  );
  static const userPhone = ffai.ProjectAppStateFieldHandle(
    name: "userPhone",
    key: "7oywkj1j",
    typeName: "String",
    persisted: true,
  );
  static const all = <ffai.ProjectAppStateFieldHandle>[
    authToken,
    cartItems,
    isLoggedIn,
    userAddress,
    userEmail,
    userId,
    userName,
    userPhone,
  ];
}

