// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;
import 'components/product_card.dart' show ProductCardComponentHandle;

abstract final class Components {
  static final productCard = ProductCardComponentHandle();
  static final all = <ffai.ProjectComponentHandle>[
    productCard,
  ];
}
