// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;
import 'pages/cart_page.dart' show cartPageHandle;
import 'pages/checkout_page.dart' show checkoutPageHandle;
import 'pages/login_page.dart' show loginPageHandle;
import 'pages/order_confirmation_page.dart' show orderConfirmationPageHandle;
import 'pages/order_detail_page.dart' show orderDetailPageHandle;
import 'pages/orders_page.dart' show ordersPageHandle;
import 'pages/product_detail_page.dart' show productDetailPageHandle;
import 'pages/profile_page.dart' show profilePageHandle;
import 'pages/register_page.dart' show registerPageHandle;
import 'pages/shop_home_page.dart' show shopHomePageHandle;
import 'pages/splash_page.dart' show splashPageHandle;
import 'pages/wishlist_page.dart' show wishlistPageHandle;

abstract final class Pages {
  static final cartPage = cartPageHandle;
  static final checkoutPage = checkoutPageHandle;
  static final loginPage = loginPageHandle;
  static final orderConfirmationPage = orderConfirmationPageHandle;
  static final orderDetailPage = orderDetailPageHandle;
  static final ordersPage = ordersPageHandle;
  static final productDetailPage = productDetailPageHandle;
  static final profilePage = profilePageHandle;
  static final registerPage = registerPageHandle;
  static final shopHomePage = shopHomePageHandle;
  static final splashPage = splashPageHandle;
  static final wishlistPage = wishlistPageHandle;
  static final all = <ffai.ProjectPageHandle>[
    cartPage,
    checkoutPage,
    loginPage,
    orderConfirmationPage,
    orderDetailPage,
    ordersPage,
    productDetailPage,
    profilePage,
    registerPage,
    shopHomePage,
    splashPage,
    wishlistPage,
  ];
}
