// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

abstract final class Project {
  static const id = "sole-craft-p-h-fos3c5";
  static const name = "SoleCraftPH";
  static const sdkMetaVersion = 3;
}
