// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'dart:collection';

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

abstract final class Enums {
  static const all = <ffai.EnumHandle>[];
}

abstract final class Structs {
  static final ffai.StructHandle apiUser = ffai.StructHandle(
    "ApiUser",
    <String, ffai.DslType>{
      "address": ffai.string,
      "email": ffai.string,
      "full_name": ffai.string,
      "id": ffai.int_,
      "phone": ffai.string,
      "role": ffai.string,
      "username": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle authData = ffai.StructHandle(
    "AuthData",
    <String, ffai.DslType>{
      "expires_at": ffai.string,
      "token": ffai.string,
      "user": Structs.apiUser,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle authResponse = ffai.StructHandle(
    "AuthResponse",
    <String, ffai.DslType>{
      "data": Structs.authData,
      "message": ffai.string,
      "success": ffai.bool_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle banner = ffai.StructHandle(
    "Banner",
    <String, ffai.DslType>{
      "id": ffai.int_,
      "link_url": ffai.string,
      "subtitle": ffai.string,
      "title": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle bannersData = ffai.StructHandle(
    "BannersData",
    <String, ffai.DslType>{
      "banners": ffai.listOf(Structs.banner),
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle bannersResponse = ffai.StructHandle(
    "BannersResponse",
    <String, ffai.DslType>{
      "data": Structs.bannersData,
      "message": ffai.string,
      "success": ffai.bool_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle cartItem = ffai.StructHandle(
    "CartItem",
    <String, ffai.DslType>{
      "image": ffai.string,
      "name": ffai.string,
      "price": ffai.double_,
      "productId": ffai.int_,
      "quantity": ffai.int_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle checkoutData = ffai.StructHandle(
    "CheckoutData",
    <String, ffai.DslType>{
      "order_id": ffai.int_,
      "status": ffai.string,
      "total_amount": ffai.double_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle checkoutResponse = ffai.StructHandle(
    "CheckoutResponse",
    <String, ffai.DslType>{
      "data": Structs.checkoutData,
      "message": ffai.string,
      "success": ffai.bool_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle detailResponse = ffai.StructHandle(
    "DetailResponse",
    <String, ffai.DslType>{
      "data": Structs.product,
      "message": ffai.string,
      "success": ffai.bool_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle orderDetailData = ffai.StructHandle(
    "OrderDetailData",
    <String, ffai.DslType>{
      "items": ffai.listOf(Structs.orderItem),
      "order": Structs.orderHead,
      "timeline": ffai.listOf(Structs.statusLog),
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle orderDetailResponse = ffai.StructHandle(
    "OrderDetailResponse",
    <String, ffai.DslType>{
      "data": Structs.orderDetailData,
      "message": ffai.string,
      "success": ffai.bool_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle orderHead = ffai.StructHandle(
    "OrderHead",
    <String, ffai.DslType>{
      "created_at": ffai.string,
      "id": ffai.int_,
      "payment_method": ffai.string,
      "status": ffai.string,
      "total_amount": ffai.double_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle orderItem = ffai.StructHandle(
    "OrderItem",
    <String, ffai.DslType>{
      "product_name": ffai.string,
      "quantity": ffai.int_,
      "subtotal": ffai.double_,
      "unit_price": ffai.double_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle orderSummary = ffai.StructHandle(
    "OrderSummary",
    <String, ffai.DslType>{
      "created_at": ffai.string,
      "id": ffai.int_,
      "item_count": ffai.int_,
      "payment_method": ffai.string,
      "status": ffai.string,
      "total_amount": ffai.double_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle ordersData = ffai.StructHandle(
    "OrdersData",
    <String, ffai.DslType>{
      "orders": ffai.listOf(Structs.orderSummary),
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle ordersResponse = ffai.StructHandle(
    "OrdersResponse",
    <String, ffai.DslType>{
      "data": Structs.ordersData,
      "message": ffai.string,
      "success": ffai.bool_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle product = ffai.StructHandle(
    "Product",
    <String, ffai.DslType>{
      "badge": ffai.string,
      "category": ffai.string,
      "description": ffai.string,
      "id": ffai.int_,
      "image": ffai.string,
      "name": ffai.string,
      "on_sale": ffai.bool_,
      "price": ffai.double_,
      "sale_price": ffai.double_,
      "stock": ffai.int_,
      "subcategory": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle productsData = ffai.StructHandle(
    "ProductsData",
    <String, ffai.DslType>{
      "products": ffai.listOf(Structs.product),
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle productsResponse = ffai.StructHandle(
    "ProductsResponse",
    <String, ffai.DslType>{
      "data": Structs.productsData,
      "message": ffai.string,
      "success": ffai.bool_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle review = ffai.StructHandle(
    "Review",
    <String, ffai.DslType>{
      "comment": ffai.string,
      "created_at": ffai.string,
      "id": ffai.int_,
      "rating": ffai.int_,
      "reviewer": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle reviewsData = ffai.StructHandle(
    "ReviewsData",
    <String, ffai.DslType>{
      "reviews": ffai.listOf(Structs.review),
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle reviewsResponse = ffai.StructHandle(
    "ReviewsResponse",
    <String, ffai.DslType>{
      "data": Structs.reviewsData,
      "message": ffai.string,
      "success": ffai.bool_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle statusLog = ffai.StructHandle(
    "StatusLog",
    <String, ffai.DslType>{
      "created_at": ffai.string,
      "note": ffai.string,
      "status": ffai.string,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle wishlistData = ffai.StructHandle(
    "WishlistData",
    <String, ffai.DslType>{
      "wishlist": ffai.listOf(Structs.product),
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final ffai.StructHandle wishlistResponse = ffai.StructHandle(
    "WishlistResponse",
    <String, ffai.DslType>{
      "data": Structs.wishlistData,
      "message": ffai.string,
      "success": ffai.bool_,
    },
    description: ffai.generatedProjectStructDescription,
  );
  static final all = <ffai.StructHandle>[
    apiUser,
    authData,
    authResponse,
    banner,
    bannersData,
    bannersResponse,
    cartItem,
    checkoutData,
    checkoutResponse,
    detailResponse,
    orderDetailData,
    orderDetailResponse,
    orderHead,
    orderItem,
    orderSummary,
    ordersData,
    ordersResponse,
    product,
    productsData,
    productsResponse,
    review,
    reviewsData,
    reviewsResponse,
    statusLog,
    wishlistData,
    wishlistResponse,
  ];
}

abstract final class Collections {
  static const all = <ffai.ProjectCollectionHandle>[];
}

abstract final class Tables {
  static const all = <ffai.ProjectTableHandle>[];
}

abstract final class CustomCode {
  static const functions = <String>[
    "cartToJson",
  ];
  static const actions = <String>[
  ];
  static const widgets = <String>[
  ];
}

