// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final accountHandle = ffai.ProjectPageHandle<AccountParams, AccountState>(
  name: "Account",
  key: "Scaffold_a1gkzfdc",
  route: "account",
  params: const AccountParams(),
  state: const AccountState(),
  widgets: AccountWidgets.tree,
);

final class AccountParams {
  const AccountParams();
}

final class AccountState {
  const AccountState();
}

abstract final class AccountWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_a1gkzfdc",
      type: "Scaffold",
      path: "Account",
      name: "Account",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_shgtrxuj",
            type: "AppBar",
            path: "Account.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_zkfarg64",
                  type: "Text",
                  path: "Account.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Account",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_qef7warh",
            type: "Column",
            path: "Account.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Row_24dp4mig",
                type: "Row",
                path: "Account.body[0].children[0]",
                name: "Row",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_5j3986vq",
                    type: "Container",
                    path: "Account.body[0].children[0].children[0]",
                    name: "Avatar",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_46tahf47",
                        type: "Text",
                        path: "Account.body[0].children[0].children[0].children[0]",
                        name: "Avatar Text",
                        text: "SC",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_ivb1joe3",
                    type: "Column",
                    path: "Account.body[0].children[0].children[1]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_h5xc1ixt",
                        type: "Text",
                        path: "Account.body[0].children[0].children[1].children[0]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_zjw3bo74",
                        type: "Text",
                        path: "Account.body[0].children[0].children[1].children[1]",
                        name: "Text",
                        text: "Guest",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_ebao1mvt",
                        type: "Text",
                        path: "Account.body[0].children[0].children[1].children[2]",
                        name: "Text",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_di75aaoe",
                type: "Container",
                path: "Account.body[0].children[1]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_byi1uknh",
                    type: "Column",
                    path: "Account.body[0].children[1].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_ofvudvjl",
                        type: "Text",
                        path: "Account.body[0].children[1].children[0].children[0]",
                        name: "Text",
                        text: "You are not signed in",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_0lzt4wyi",
                        type: "Button",
                        path: "Account.body[0].children[1].children[0].children[1]",
                        name: "Button",
                        text: "Sign in",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_a2p9gfu0",
                        type: "Button",
                        path: "Account.body[0].children[1].children[0].children[2]",
                        name: "Button",
                        text: "Create an account",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ListTile_pvn5iupa",
                type: "ListTile",
                path: "Account.body[0].children[2]",
                name: "addressesTile",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ListTile_ra3qqzuv",
                type: "ListTile",
                path: "Account.body[0].children[3]",
                name: "accountProfileTile",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ListTile_yxcqduiu",
                type: "ListTile",
                path: "Account.body[0].children[4]",
                name: "accountNotificationsTile",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ListTile_nfw3mvu8",
                type: "ListTile",
                path: "Account.body[0].children[5]",
                name: "accountWishlistTile",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ListTile_81kcu172",
                type: "ListTile",
                path: "Account.body[0].children[6]",
                name: "ListTile",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ListTile_vjqn585s",
                type: "ListTile",
                path: "Account.body[0].children[7]",
                name: "ListTile",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ListTile_dak60bnf",
                type: "ListTile",
                path: "Account.body[0].children[8]",
                name: "ListTile",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListTile_yulwqsdg",
                type: "ListTile",
                path: "Account.body[0].children[9]",
                name: "accountHelpTile",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_e62wmj76",
                type: "Button",
                path: "Account.body[0].children[10]",
                name: "Button",
                text: "Sign out",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

