// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final addressesHandle = ffai.ProjectPageHandle<AddressesParams, AddressesState>(
  name: "Addresses",
  key: "Scaffold_m53xc13y",
  route: "addresses",
  params: const AddressesParams(),
  state: const AddressesState(),
  widgets: AddressesWidgets.tree,
);

final class AddressesParams {
  const AddressesParams();
}

final class AddressesState {
  const AddressesState();
  ffai.ProjectStateFieldHandle get editingId =>
      const ffai.ProjectStateFieldHandle(
        name: "editingId",
        key: "k3aqy823",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get formOpen =>
      const ffai.ProjectStateFieldHandle(
        name: "formOpen",
        key: "82ruxwbj",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get pin =>
      const ffai.ProjectStateFieldHandle(
        name: "pin",
        key: "ishws2nl",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get saved =>
      const ffai.ProjectStateFieldHandle(
        name: "saved",
        key: "mgkys2yn",
        typeName: "List<DataStruct<AddressRow>>",
      );
}

abstract final class AddressesWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_m53xc13y",
      type: "Scaffold",
      path: "Addresses",
      name: "Addresses",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_e2xqdavx",
            type: "AppBar",
            path: "Addresses.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_qnhcfoh3",
                  type: "Text",
                  path: "Addresses.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Delivery Addresses",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_lp21y1q8",
            type: "Column",
            path: "Addresses.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Text_sjuru26y",
                type: "Text",
                path: "Addresses.body[0].children[0]",
                name: "addressesHeading",
                text: "Saved addresses",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_40n3er44",
                type: "ListView",
                path: "Addresses.body[0].children[1]",
                name: "addressList",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_fman5gsm",
                    type: "Container",
                    path: "Addresses.body[0].children[1].children[0]",
                    name: "addressCard",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_efi3ukpw",
                        type: "Column",
                        path: "Addresses.body[0].children[1].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_w06hv2wu",
                            type: "Row",
                            path: "Addresses.body[0].children[1].children[0].children[0].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_knewqiga",
                                type: "Text",
                                path: "Addresses.body[0].children[1].children[0].children[0].children[0].children[0]",
                                name: "addressLabel",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_j4sy4b6y",
                                type: "Text",
                                path: "Addresses.body[0].children[1].children[0].children[0].children[0].children[1]",
                                name: "addressDefaultTag",
                                text: "Default",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_5qhi5uy2",
                            type: "Text",
                            path: "Addresses.body[0].children[1].children[0].children[0].children[1]",
                            name: "addressLine",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_n1oz1qzj",
                            type: "Text",
                            path: "Addresses.body[0].children[1].children[0].children[0].children[2]",
                            name: "addressPhone",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_4s65j54t",
                            type: "Text",
                            path: "Addresses.body[0].children[1].children[0].children[0].children[3]",
                            name: "addressPinned",
                            text: "Pinned on the map",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Row_ccx9vx5a",
                            type: "Row",
                            path: "Addresses.body[0].children[1].children[0].children[0].children[4]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_k6s1ay3a",
                                type: "Container",
                                path: "Addresses.body[0].children[1].children[0].children[0].children[4].children[0]",
                                name: "makeDefault",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_9jpt24fn",
                                    type: "Text",
                                    path: "Addresses.body[0].children[1].children[0].children[0].children[4].children[0].children[0]",
                                    name: "Text",
                                    text: "Make default",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_7k7uxuos",
                                type: "Container",
                                path: "Addresses.body[0].children[1].children[0].children[0].children[4].children[1]",
                                name: "deleteAddressAction",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_tdocbrpr",
                                    type: "Text",
                                    path: "Addresses.body[0].children[1].children[0].children[0].children[4].children[1].children[0]",
                                    name: "Text",
                                    text: "Delete",
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_c7s7yfvu",
                type: "Text",
                path: "Addresses.body[0].children[2]",
                name: "addressesEmpty",
                text: "No saved addresses yet. Add one below and checkout will fill itself in next time.",
              ),
              ffai.ProjectWidgetHandle(
                key: "Divider_yghktyiw",
                type: "Divider",
                path: "Addresses.body[0].children[3]",
                name: "Divider",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_oz3k4olf",
                type: "Text",
                path: "Addresses.body[0].children[4]",
                name: "addFormHeading",
                text: "Add an address",
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_ya1qalx9",
                type: "TextField",
                path: "Addresses.body[0].children[5]",
                name: "addrLabel",
                text: "Label — Home, Work, Mum's",
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_5gketlsz",
                type: "TextField",
                path: "Addresses.body[0].children[6]",
                name: "addrRecipient",
                text: "Who receives it",
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_ga4c02y7",
                type: "TextField",
                path: "Addresses.body[0].children[7]",
                name: "addrPhone",
                text: "Contact number",
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_bnm5k1u4",
                type: "TextField",
                path: "Addresses.body[0].children[8]",
                name: "addrLine",
                text: "House / street / barangay / city",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_zss3llaf",
                type: "Button",
                path: "Addresses.body[0].children[9]",
                name: "useMyLocation",
                text: "Use my current location",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_eqfczwlu",
                type: "Text",
                path: "Addresses.body[0].children[10]",
                name: "pinnedNotice",
                text: "Location pinned",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_vu4f5z6e",
                type: "Button",
                path: "Addresses.body[0].children[11]",
                name: "saveAddressButton",
                text: "Save address",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

