// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final checkoutHandle = ffai.ProjectPageHandle<CheckoutParams, CheckoutState>(
  name: "Checkout",
  key: "Scaffold_gqw69z45",
  route: "place-order",
  params: const CheckoutParams(),
  state: const CheckoutState(),
  widgets: CheckoutWidgets.tree,
);

final class CheckoutParams {
  const CheckoutParams();
}

final class CheckoutState {
  const CheckoutState();
  ffai.ProjectStateFieldHandle get address =>
      const ffai.ProjectStateFieldHandle(
        name: "address",
        key: "rvnqdddq",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get email =>
      const ffai.ProjectStateFieldHandle(
        name: "email",
        key: "bqtdkxqp",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get fullName =>
      const ffai.ProjectStateFieldHandle(
        name: "fullName",
        key: "syxb2jeq",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get payMethod =>
      const ffai.ProjectStateFieldHandle(
        name: "payMethod",
        key: "eu8nilwt",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get phone =>
      const ffai.ProjectStateFieldHandle(
        name: "phone",
        key: "n3ep9gef",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get placing =>
      const ffai.ProjectStateFieldHandle(
        name: "placing",
        key: "tvjy0ehp",
        typeName: "Boolean",
      );
}

abstract final class CheckoutWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_gqw69z45",
      type: "Scaffold",
      path: "Checkout",
      name: "Checkout",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_upj4n813",
            type: "AppBar",
            path: "Checkout.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_jdj4csk1",
                  type: "Text",
                  path: "Checkout.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Checkout",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_8m03monh",
            type: "Column",
            path: "Checkout.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_8vvj4mkl",
                type: "Container",
                path: "Checkout.body[0].children[0]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_aqzlb46m",
                    type: "Row",
                    path: "Checkout.body[0].children[0].children[0]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Icon_oepyqtl9",
                        type: "Icon",
                        path: "Checkout.body[0].children[0].children[0].children[0]",
                        name: "Icon",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_ec5fm6g2",
                        type: "Text",
                        path: "Checkout.body[0].children[0].children[0].children[1]",
                        name: "Text",
                        text: "Checking out as a guest. Sign in to keep this order in your history.",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_vcm51g2m",
                type: "Text",
                path: "Checkout.body[0].children[1]",
                name: "Text",
                text: "Shipping details",
              ),
              ffai.ProjectWidgetHandle(
                key: "Form_cwrpxwfx",
                type: "Form",
                path: "Checkout.body[0].children[2]",
                name: "checkoutForm",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_h5nef4rt",
                    type: "Column",
                    path: "Checkout.body[0].children[2].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "TextField_34iw5du7",
                        type: "TextField",
                        path: "Checkout.body[0].children[2].children[0].children[0]",
                        name: "coName",
                        text: "Full name",
                        triggers: const <String>[
                          "ON_TEXTFIELD_CHANGE",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "TextField_zxgfjsxb",
                        type: "TextField",
                        path: "Checkout.body[0].children[2].children[0].children[1]",
                        name: "coEmail",
                        text: "Email",
                        triggers: const <String>[
                          "ON_TEXTFIELD_CHANGE",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "TextField_bng08kxc",
                        type: "TextField",
                        path: "Checkout.body[0].children[2].children[0].children[2]",
                        name: "coAddress",
                        text: "Delivery address",
                        triggers: const <String>[
                          "ON_TEXTFIELD_CHANGE",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "TextField_9li215mu",
                        type: "TextField",
                        path: "Checkout.body[0].children[2].children[0].children[3]",
                        name: "coPhone",
                        text: "Mobile number",
                        triggers: const <String>[
                          "ON_TEXTFIELD_CHANGE",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_l347dsvx",
                type: "Text",
                path: "Checkout.body[0].children[3]",
                name: "Text",
                text: "Payment method",
              ),
              ffai.ProjectWidgetHandle(
                key: "Row_fxhbf771",
                type: "Row",
                path: "Checkout.body[0].children[4]",
                name: "Row",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_iuz96ohv",
                    type: "Container",
                    path: "Checkout.body[0].children[4].children[0]",
                    name: "Container",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_6b63o2ge",
                        type: "Column",
                        path: "Checkout.body[0].children[4].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_enyrmuwo",
                            type: "Icon",
                            path: "Checkout.body[0].children[4].children[0].children[0].children[0]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Icon_9shpka7h",
                            type: "Icon",
                            path: "Checkout.body[0].children[4].children[0].children[0].children[1]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_hk3y2940",
                            type: "Text",
                            path: "Checkout.body[0].children[4].children[0].children[0].children[2]",
                            name: "Text",
                            text: "Cash on Delivery",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_ebi2q81v",
                    type: "Container",
                    path: "Checkout.body[0].children[4].children[1]",
                    name: "Container",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_sgg1jr1f",
                        type: "Column",
                        path: "Checkout.body[0].children[4].children[1].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_gmofk040",
                            type: "Icon",
                            path: "Checkout.body[0].children[4].children[1].children[0].children[0]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Icon_aq5vns33",
                            type: "Icon",
                            path: "Checkout.body[0].children[4].children[1].children[0].children[1]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_u4aq4q7g",
                            type: "Text",
                            path: "Checkout.body[0].children[4].children[1].children[0].children[2]",
                            name: "Text",
                            text: "GCash",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_43akn8dy",
                    type: "Container",
                    path: "Checkout.body[0].children[4].children[2]",
                    name: "Container",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_ttwk9fub",
                        type: "Column",
                        path: "Checkout.body[0].children[4].children[2].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_iwubqunj",
                            type: "Icon",
                            path: "Checkout.body[0].children[4].children[2].children[0].children[0]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Icon_vy7dz91n",
                            type: "Icon",
                            path: "Checkout.body[0].children[4].children[2].children[0].children[1]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_lf8ge8ja",
                            type: "Text",
                            path: "Checkout.body[0].children[4].children[2].children[0].children[2]",
                            name: "Text",
                            text: "Card",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Divider_26zla8m6",
                type: "Divider",
                path: "Checkout.body[0].children[5]",
                name: "Divider",
              ),
              ffai.ProjectWidgetHandle(
                key: "Row_mbzwpgog",
                type: "Row",
                path: "Checkout.body[0].children[6]",
                name: "Row",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_26f7ptke",
                    type: "Text",
                    path: "Checkout.body[0].children[6].children[0]",
                    name: "Text",
                    text: "Items",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_013fmb3a",
                    type: "Text",
                    path: "Checkout.body[0].children[6].children[1]",
                    name: "Text",
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Row_fsz3wtzj",
                type: "Row",
                path: "Checkout.body[0].children[7]",
                name: "Row",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_d87xasym",
                    type: "Text",
                    path: "Checkout.body[0].children[7].children[0]",
                    name: "Text",
                    text: "Order total",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_hb4ipyla",
                    type: "Text",
                    path: "Checkout.body[0].children[7].children[1]",
                    name: "Text",
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_ye04uoud",
                type: "Button",
                path: "Checkout.body[0].children[8]",
                name: "Button",
                text: "Place Order",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ProgressBar_dmcpk0nh",
                type: "ProgressBar",
                path: "Checkout.body[0].children[9]",
                name: "ProgressBar",
              ),
            ],
          ),
        ],
      },
    ),
  );
}

