// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final confirmedHandle = ffai.ProjectPageHandle<ConfirmedParams, ConfirmedState>(
  name: "Confirmed",
  key: "Scaffold_luddsfp0",
  route: "confirmed",
  params: const ConfirmedParams(),
  state: const ConfirmedState(),
  widgets: ConfirmedWidgets.tree,
);

final class ConfirmedParams {
  const ConfirmedParams();
  ffai.ProjectParamHandle get orderId =>
      const ffai.ProjectParamHandle(
        name: "orderId",
        key: "6otzq4sg",
        typeName: "Integer",
      );
}

final class ConfirmedState {
  const ConfirmedState();
  ffai.ProjectStateFieldHandle get order =>
      const ffai.ProjectStateFieldHandle(
        name: "order",
        key: "u2tq6wk9",
        typeName: "DataStruct<OrderRow>",
      );
}

abstract final class ConfirmedWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_luddsfp0",
      type: "Scaffold",
      path: "Confirmed",
      name: "Confirmed",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_5x0sk64r",
            type: "AppBar",
            path: "Confirmed.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_0qel3dmj",
                  type: "Text",
                  path: "Confirmed.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Order Placed",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_j721v85a",
            type: "Column",
            path: "Confirmed.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Icon_d5h5pmd8",
                type: "Icon",
                path: "Confirmed.body[0].children[0]",
                name: "Icon",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_vl6tty48",
                type: "Text",
                path: "Confirmed.body[0].children[1]",
                name: "Text",
                text: "Thank you!",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_epdwdnvu",
                type: "Text",
                path: "Confirmed.body[0].children[2]",
                name: "Text",
                text: "Your order has been placed on SoleCraftPH.",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_gwkyy1nr",
                type: "Container",
                path: "Confirmed.body[0].children[3]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_uhwex2xs",
                    type: "Column",
                    path: "Confirmed.body[0].children[3].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_jvsqkmkw",
                        type: "Row",
                        path: "Confirmed.body[0].children[3].children[0].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_6960dsfa",
                            type: "Text",
                            path: "Confirmed.body[0].children[3].children[0].children[0].children[0]",
                            name: "Text",
                            text: "Order number",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_xskgwsys",
                            type: "Text",
                            path: "Confirmed.body[0].children[3].children[0].children[0].children[1]",
                            name: "Text",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_i879vfms",
                        type: "Row",
                        path: "Confirmed.body[0].children[3].children[0].children[1]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_5t1ipajn",
                            type: "Text",
                            path: "Confirmed.body[0].children[3].children[0].children[1].children[0]",
                            name: "Text",
                            text: "Status",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_2ljozhdf",
                            type: "Text",
                            path: "Confirmed.body[0].children[3].children[0].children[1].children[1]",
                            name: "Text",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_bmnxc22g",
                        type: "Row",
                        path: "Confirmed.body[0].children[3].children[0].children[2]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_4xoe34kl",
                            type: "Text",
                            path: "Confirmed.body[0].children[3].children[0].children[2].children[0]",
                            name: "Text",
                            text: "Amount",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_ovmxx6g1",
                            type: "Text",
                            path: "Confirmed.body[0].children[3].children[0].children[2].children[1]",
                            name: "Text",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_4bxfqn66",
                type: "Button",
                path: "Confirmed.body[0].children[4]",
                name: "Button",
                text: "Continue shopping",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

