// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final developersHandle = ffai.ProjectPageHandle<DevelopersParams, DevelopersState>(
  name: "Developers",
  key: "Scaffold_zlyt3hdv",
  route: "developers",
  params: const DevelopersParams(),
  state: const DevelopersState(),
  widgets: DevelopersWidgets.tree,
);

final class DevelopersParams {
  const DevelopersParams();
}

final class DevelopersState {
  const DevelopersState();
}

abstract final class DevelopersWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_zlyt3hdv",
      type: "Scaffold",
      path: "Developers",
      name: "Developers",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_7ho1jqym",
            type: "AppBar",
            path: "Developers.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_4v49xjwq",
                  type: "Text",
                  path: "Developers.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "The Developers",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_tbtubd4k",
            type: "Column",
            path: "Developers.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Text_oq4e2ln3",
                type: "Text",
                path: "Developers.body[0].children[0]",
                name: "Text",
                text: "Group 9, the five of us who built SoleCraftPH, from the storefront and the admin panel to the Android app.",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_jpw7z9y4",
                type: "Container",
                path: "Developers.body[0].children[1]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_2kxi27xz",
                    type: "Column",
                    path: "Developers.body[0].children[1].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_n3xoxiie",
                        type: "Row",
                        path: "Developers.body[0].children[1].children[0].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_websn4m8",
                            type: "Container",
                            path: "Developers.body[0].children[1].children[0].children[0].children[0]",
                            name: "avatarBB",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_x3kd1or5",
                            type: "Text",
                            path: "Developers.body[0].children[1].children[0].children[0].children[1]",
                            name: "Text",
                            text: "Brian Ballano",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Divider_0tn8v668",
                        type: "Divider",
                        path: "Developers.body[0].children[1].children[0].children[1]",
                        name: "Divider",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_57ifv64a",
                        type: "Row",
                        path: "Developers.body[0].children[1].children[0].children[2]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_sbxuwa8b",
                            type: "Container",
                            path: "Developers.body[0].children[1].children[0].children[2].children[0]",
                            name: "avatarER",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_3alccfjt",
                            type: "Text",
                            path: "Developers.body[0].children[1].children[0].children[2].children[1]",
                            name: "Text",
                            text: "Erika Joan Del Rosario",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Divider_vyh3na9q",
                        type: "Divider",
                        path: "Developers.body[0].children[1].children[0].children[3]",
                        name: "Divider",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_3n2ifyj7",
                        type: "Row",
                        path: "Developers.body[0].children[1].children[0].children[4]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_9gyrenn7",
                            type: "Container",
                            path: "Developers.body[0].children[1].children[0].children[4].children[0]",
                            name: "avatarJB",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_q1bo4d27",
                            type: "Text",
                            path: "Developers.body[0].children[1].children[0].children[4].children[1]",
                            name: "Text",
                            text: "John Lawrence Balitos",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Divider_rtmnnapc",
                        type: "Divider",
                        path: "Developers.body[0].children[1].children[0].children[5]",
                        name: "Divider",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_d2nt2rgi",
                        type: "Row",
                        path: "Developers.body[0].children[1].children[0].children[6]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_tdv7eodo",
                            type: "Container",
                            path: "Developers.body[0].children[1].children[0].children[6].children[0]",
                            name: "avatarKL",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_1l4wq35o",
                            type: "Text",
                            path: "Developers.body[0].children[1].children[0].children[6].children[1]",
                            name: "Text",
                            text: "Keanu Florenz Licup",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Divider_pd6vwzm2",
                        type: "Divider",
                        path: "Developers.body[0].children[1].children[0].children[7]",
                        name: "Divider",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_bhq0jmta",
                        type: "Row",
                        path: "Developers.body[0].children[1].children[0].children[8]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_f0tlj51b",
                            type: "Container",
                            path: "Developers.body[0].children[1].children[0].children[8].children[0]",
                            name: "avatarPB",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_nxu4brdg",
                            type: "Text",
                            path: "Developers.body[0].children[1].children[0].children[8].children[1]",
                            name: "Text",
                            text: "Paul Francis Balboa",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

