// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final helpHandle = ffai.ProjectPageHandle<HelpParams, HelpState>(
  name: "Help",
  key: "Scaffold_7fox2l41",
  route: "help",
  params: const HelpParams(),
  state: const HelpState(),
  widgets: HelpWidgets.tree,
);

final class HelpParams {
  const HelpParams();
}

final class HelpState {
  const HelpState();
  ffai.ProjectStateFieldHandle get pages =>
      const ffai.ProjectStateFieldHandle(
        name: "pages",
        key: "cltk80jd",
        typeName: "DataStruct<InfoMenu>",
      );
}

abstract final class HelpWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_7fox2l41",
      type: "Scaffold",
      path: "Help",
      name: "Help",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_2tr50ycb",
            type: "AppBar",
            path: "Help.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_m8z9i4ab",
                  type: "Text",
                  path: "Help.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Help",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_oyblvgv8",
            type: "Column",
            path: "Help.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Text_cab4jbio",
                type: "Text",
                path: "Help.body[0].children[0]",
                name: "Text",
                text: "Contact support",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_3d5o8ub7",
                type: "Text",
                path: "Help.body[0].children[1]",
                name: "Text",
                text: "Signed in? Leave your name and email blank and we will use your account details.",
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_g5776rwb",
                type: "TextField",
                path: "Help.body[0].children[2]",
                name: "hpName",
                text: "Your name",
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_fmv3m9j4",
                type: "TextField",
                path: "Help.body[0].children[3]",
                name: "hpEmail",
                text: "Email",
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_ctkxco9o",
                type: "TextField",
                path: "Help.body[0].children[4]",
                name: "hpSubject",
                text: "Subject",
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_jj1f6bwm",
                type: "TextField",
                path: "Help.body[0].children[5]",
                name: "hpMessage",
                text: "Message",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_jen68k44",
                type: "Button",
                path: "Help.body[0].children[6]",
                name: "hpSend",
                text: "Send message",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_gs3ioat0",
                type: "Text",
                path: "Help.body[0].children[7]",
                name: "Text",
                text: "About SoleCraftPH",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_ktnii6z9",
                type: "ListView",
                path: "Help.body[0].children[8]",
                name: "ListView",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "ListTile_f78n6a0l",
                    type: "ListTile",
                    path: "Help.body[0].children[8].children[0]",
                    name: "ListTile",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

