// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final infoPageHandle = ffai.ProjectPageHandle<InfoPageParams, InfoPageState>(
  name: "InfoPage",
  key: "Scaffold_at60cp5j",
  route: "info",
  params: const InfoPageParams(),
  state: const InfoPageState(),
  widgets: InfoPageWidgets.tree,
);

final class InfoPageParams {
  const InfoPageParams();
  ffai.ProjectParamHandle get slug =>
      const ffai.ProjectParamHandle(
        name: "slug",
        key: "rrl2lxo0",
        typeName: "String",
      );
}

final class InfoPageState {
  const InfoPageState();
  ffai.ProjectStateFieldHandle get page =>
      const ffai.ProjectStateFieldHandle(
        name: "page",
        key: "eqvz1g6j",
        typeName: "DataStruct<InfoPage>",
      );
}

abstract final class InfoPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_at60cp5j",
      type: "Scaffold",
      path: "InfoPage",
      name: "InfoPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_54t95jcv",
            type: "AppBar",
            path: "InfoPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_nshmxear",
                  type: "Text",
                  path: "InfoPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "SoleCraftPH",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_c609tybx",
            type: "Column",
            path: "InfoPage.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Text_x5wdh00k",
                type: "Text",
                path: "InfoPage.body[0].children[0]",
                name: "Text",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_mefsowa8",
                type: "Text",
                path: "InfoPage.body[0].children[1]",
                name: "Text",
              ),
            ],
          ),
        ],
      },
    ),
  );
}

