// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final myOrdersHandle = ffai.ProjectPageHandle<MyOrdersParams, MyOrdersState>(
  name: "MyOrders",
  key: "Scaffold_wio6p18q",
  route: "my-orders",
  params: const MyOrdersParams(),
  state: const MyOrdersState(),
  widgets: MyOrdersWidgets.tree,
);

final class MyOrdersParams {
  const MyOrdersParams();
}

final class MyOrdersState {
  const MyOrdersState();
  ffai.ProjectStateFieldHandle get isLoading =>
      const ffai.ProjectStateFieldHandle(
        name: "isLoading",
        key: "ejgd3w5u",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get orders =>
      const ffai.ProjectStateFieldHandle(
        name: "orders",
        key: "09nf77sd",
        typeName: "List<DataStruct<OrderRow>>",
      );
}

abstract final class MyOrdersWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_wio6p18q",
      type: "Scaffold",
      path: "MyOrders",
      name: "MyOrders",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_0r5kn2lj",
            type: "AppBar",
            path: "MyOrders.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_n28bapbi",
                  type: "Text",
                  path: "MyOrders.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "My Orders",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_6i38mcw3",
            type: "Column",
            path: "MyOrders.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_0tcphlm6",
                type: "Column",
                path: "MyOrders.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Icon_5ad4nxol",
                    type: "Icon",
                    path: "MyOrders.body[0].children[0].children[0]",
                    name: "Icon",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_m6c6vpq5",
                    type: "Text",
                    path: "MyOrders.body[0].children[0].children[1]",
                    name: "Text",
                    text: "Sign in to see your orders",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_u8gif52r",
                    type: "Text",
                    path: "MyOrders.body[0].children[0].children[2]",
                    name: "Text",
                    text: "Orders you place while signed in are saved to your account.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_jvxfq2dg",
                    type: "Button",
                    path: "MyOrders.body[0].children[0].children[3]",
                    name: "Button",
                    text: "Sign in",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ProgressBar_x41l9z0y",
                type: "ProgressBar",
                path: "MyOrders.body[0].children[1]",
                name: "ProgressBar",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_ko415scl",
                type: "ListView",
                path: "MyOrders.body[0].children[2]",
                name: "ListView",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_x3gjkj3t",
                    type: "Container",
                    path: "MyOrders.body[0].children[2].children[0]",
                    name: "Container",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_t4musqqp",
                        type: "Column",
                        path: "MyOrders.body[0].children[2].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_d7j4by5y",
                            type: "Row",
                            path: "MyOrders.body[0].children[2].children[0].children[0].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_bztfz470",
                                type: "Text",
                                path: "MyOrders.body[0].children[2].children[0].children[0].children[0].children[0]",
                                name: "Text",
                                text: "Order #",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_0cm12rss",
                                type: "Text",
                                path: "MyOrders.body[0].children[2].children[0].children[0].children[0].children[1]",
                                name: "Text",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Row_xdwgsgux",
                            type: "Row",
                            path: "MyOrders.body[0].children[2].children[0].children[0].children[1]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_cbsp3ss0",
                                type: "Container",
                                path: "MyOrders.body[0].children[2].children[0].children[0].children[1].children[0]",
                                name: "Container",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_iue0zak6",
                                    type: "Text",
                                    path: "MyOrders.body[0].children[2].children[0].children[0].children[1].children[0].children[0]",
                                    name: "Text",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_6ogjczfo",
                                type: "Text",
                                path: "MyOrders.body[0].children[2].children[0].children[0].children[1].children[1]",
                                name: "Text",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_09mdfn36",
                            type: "Text",
                            path: "MyOrders.body[0].children[2].children[0].children[0].children[2]",
                            name: "Text",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

