// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final notificationsHandle = ffai.ProjectPageHandle<NotificationsParams, NotificationsState>(
  name: "Notifications",
  key: "Scaffold_an6qmjg0",
  route: "notifications",
  params: const NotificationsParams(),
  state: const NotificationsState(),
  widgets: NotificationsWidgets.tree,
);

final class NotificationsParams {
  const NotificationsParams();
}

final class NotificationsState {
  const NotificationsState();
  ffai.ProjectStateFieldHandle get feed =>
      const ffai.ProjectStateFieldHandle(
        name: "feed",
        key: "klee5r5r",
        typeName: "DataStruct<NotificationList>",
      );
}

abstract final class NotificationsWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_an6qmjg0",
      type: "Scaffold",
      path: "Notifications",
      name: "Notifications",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_s1ihv52i",
            type: "AppBar",
            path: "Notifications.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_3f5hzo58",
                  type: "Text",
                  path: "Notifications.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Notifications",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_e8bqu00s",
            type: "Column",
            path: "Notifications.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Row_dw16rkxa",
                type: "Row",
                path: "Notifications.body[0].children[0]",
                name: "Row",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_mcqs516e",
                    type: "Text",
                    path: "Notifications.body[0].children[0].children[0]",
                    name: "unreadCount",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_zph5u7sa",
                    type: "Button",
                    path: "Notifications.body[0].children[0].children[1]",
                    name: "markAllRead",
                    text: "Mark all read",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_mp2343sk",
                type: "Text",
                path: "Notifications.body[0].children[1]",
                name: "notificationsEmpty",
                text: "Nothing here yet. Order updates will show up as they happen.",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_399slaet",
                type: "ListView",
                path: "Notifications.body[0].children[2]",
                name: "ListView",
                triggers: const <String>[
                  "ON_PULL_TO_REFRESH",
                ],
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_3awzjtap",
                    type: "Container",
                    path: "Notifications.body[0].children[2].children[0]",
                    name: "Container",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_utowk4fk",
                        type: "Row",
                        path: "Notifications.body[0].children[2].children[0].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_p4cqe70m",
                            type: "Container",
                            path: "Notifications.body[0].children[2].children[0].children[0].children[0]",
                            name: "Container",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Column_bgqyjke3",
                            type: "Column",
                            path: "Notifications.body[0].children[2].children[0].children[0].children[1]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_b2zzx67o",
                                type: "Text",
                                path: "Notifications.body[0].children[2].children[0].children[0].children[1].children[0]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_4sgmbdet",
                                type: "Text",
                                path: "Notifications.body[0].children[2].children[0].children[0].children[1].children[1]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_p3hznpe9",
                                type: "Text",
                                path: "Notifications.body[0].children[2].children[0].children[0].children[1].children[2]",
                                name: "Text",
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

