// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final orderDetailHandle = ffai.ProjectPageHandle<OrderDetailParams, OrderDetailState>(
  name: "OrderDetail",
  key: "Scaffold_ew41azrf",
  route: "order-detail",
  params: const OrderDetailParams(),
  state: const OrderDetailState(),
  widgets: OrderDetailWidgets.tree,
);

final class OrderDetailParams {
  const OrderDetailParams();
  ffai.ProjectParamHandle get orderId =>
      const ffai.ProjectParamHandle(
        name: "orderId",
        key: "5nqmq9xv",
        typeName: "Integer",
      );
}

final class OrderDetailState {
  const OrderDetailState();
  ffai.ProjectStateFieldHandle get loading =>
      const ffai.ProjectStateFieldHandle(
        name: "loading",
        key: "rpun96rb",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get order =>
      const ffai.ProjectStateFieldHandle(
        name: "order",
        key: "z01qm6ej",
        typeName: "DataStruct<OrderFull>",
      );
}

abstract final class OrderDetailWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_ew41azrf",
      type: "Scaffold",
      path: "OrderDetail",
      name: "OrderDetail",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_lgflg1l4",
            type: "AppBar",
            path: "OrderDetail.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_w335rbyv",
                  type: "Text",
                  path: "OrderDetail.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Order",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_1fr058kj",
            type: "Column",
            path: "OrderDetail.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "ProgressBar_9lokwdo8",
                type: "ProgressBar",
                path: "OrderDetail.body[0].children[0]",
                name: "orderLoading",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_48r49x5h",
                type: "Container",
                path: "OrderDetail.body[0].children[1]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_qoy5ibj4",
                    type: "Column",
                    path: "OrderDetail.body[0].children[1].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_4sqkdd5u",
                        type: "Text",
                        path: "OrderDetail.body[0].children[1].children[0].children[0]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_p6tf88zw",
                        type: "Row",
                        path: "OrderDetail.body[0].children[1].children[0].children[1]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_dkvx41bj",
                            type: "Text",
                            path: "OrderDetail.body[0].children[1].children[0].children[1].children[0]",
                            name: "Text",
                            text: "Placed",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_0wjdyae2",
                            type: "Text",
                            path: "OrderDetail.body[0].children[1].children[0].children[1].children[1]",
                            name: "Text",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_ed30zqud",
                        type: "Row",
                        path: "OrderDetail.body[0].children[1].children[0].children[2]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_rar5yl9g",
                            type: "Text",
                            path: "OrderDetail.body[0].children[1].children[0].children[2].children[0]",
                            name: "Text",
                            text: "Payment",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_fssdx5oo",
                            type: "Text",
                            path: "OrderDetail.body[0].children[1].children[0].children[2].children[1]",
                            name: "Text",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_r7z23fwj",
                        type: "Row",
                        path: "OrderDetail.body[0].children[1].children[0].children[3]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_s5usm7hw",
                            type: "Text",
                            path: "OrderDetail.body[0].children[1].children[0].children[3].children[0]",
                            name: "Text",
                            text: "Payment status",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_qxe7x7f7",
                            type: "Text",
                            path: "OrderDetail.body[0].children[1].children[0].children[3].children[1]",
                            name: "Text",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_gl7rxc18",
                        type: "Row",
                        path: "OrderDetail.body[0].children[1].children[0].children[4]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_6rw6tqi7",
                            type: "Text",
                            path: "OrderDetail.body[0].children[1].children[0].children[4].children[0]",
                            name: "Text",
                            text: "Total",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_oakoufuv",
                            type: "Text",
                            path: "OrderDetail.body[0].children[1].children[0].children[4].children[1]",
                            name: "Text",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_fttu2eix",
                        type: "Row",
                        path: "OrderDetail.body[0].children[1].children[0].children[5]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_yoyaxl65",
                            type: "Text",
                            path: "OrderDetail.body[0].children[1].children[0].children[5].children[0]",
                            name: "Text",
                            text: "Tracking",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_bks8ii3p",
                            type: "Text",
                            path: "OrderDetail.body[0].children[1].children[0].children[5].children[1]",
                            name: "Text",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_hdyz0qnt",
                type: "Text",
                path: "OrderDetail.body[0].children[2]",
                name: "Text",
                text: "Items",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_x5cnmiuw",
                type: "ListView",
                path: "OrderDetail.body[0].children[3]",
                name: "ListView",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_71rsfbgj",
                    type: "Row",
                    path: "OrderDetail.body[0].children[3].children[0]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_3cz8nwt2",
                        type: "Column",
                        path: "OrderDetail.body[0].children[3].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_ut9ahsnz",
                            type: "Text",
                            path: "OrderDetail.body[0].children[3].children[0].children[0].children[0]",
                            name: "Text",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_yhnil7ji",
                            type: "Text",
                            path: "OrderDetail.body[0].children[3].children[0].children[0].children[1]",
                            name: "Text",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_901nm2a9",
                        type: "Text",
                        path: "OrderDetail.body[0].children[3].children[0].children[1]",
                        name: "Text",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_zs346sue",
                type: "Text",
                path: "OrderDetail.body[0].children[4]",
                name: "Text",
                text: "Tracking history",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_ko0iuo5f",
                type: "ListView",
                path: "OrderDetail.body[0].children[5]",
                name: "ListView",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_m8b9ud1r",
                    type: "Column",
                    path: "OrderDetail.body[0].children[5].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_ruvisu4c",
                        type: "Text",
                        path: "OrderDetail.body[0].children[5].children[0].children[0]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_ehsb90sr",
                        type: "Text",
                        path: "OrderDetail.body[0].children[5].children[0].children[1]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_ijy9vsfb",
                        type: "Text",
                        path: "OrderDetail.body[0].children[5].children[0].children[2]",
                        name: "Text",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_r8kx0m2i",
                type: "Text",
                path: "OrderDetail.body[0].children[6]",
                name: "Text",
                text: "Delivering to",
              ),
              ffai.ProjectWidgetHandle(
                key: "Column_x3wk8118",
                type: "Column",
                path: "OrderDetail.body[0].children[7]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_5cmfpayt",
                    type: "Text",
                    path: "OrderDetail.body[0].children[7].children[0]",
                    name: "Text",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_hcswur02",
                    type: "Text",
                    path: "OrderDetail.body[0].children[7].children[1]",
                    name: "Text",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_o3qggqd3",
                    type: "Text",
                    path: "OrderDetail.body[0].children[7].children[2]",
                    name: "Text",
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

