// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final paymentHandle = ffai.ProjectPageHandle<PaymentParams, PaymentState>(
  name: "Payment",
  key: "Scaffold_ikj5e0qh",
  route: "payment",
  params: const PaymentParams(),
  state: const PaymentState(),
  widgets: PaymentWidgets.tree,
);

final class PaymentParams {
  const PaymentParams();
  ffai.ProjectParamHandle get orderId =>
      const ffai.ProjectParamHandle(
        name: "orderId",
        key: "k9e6qda2",
        typeName: "Integer",
      );
  ffai.ProjectParamHandle get url =>
      const ffai.ProjectParamHandle(
        name: "url",
        key: "an2tramn",
        typeName: "String",
      );
}

final class PaymentState {
  const PaymentState();
}

abstract final class PaymentWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_ikj5e0qh",
      type: "Scaffold",
      path: "Payment",
      name: "Payment",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_5v9igqet",
            type: "AppBar",
            path: "Payment.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_k2zfc81z",
                  type: "Text",
                  path: "Payment.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Complete Payment",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_sc3lfnk4",
            type: "Column",
            path: "Payment.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "WebView_q3he3wjz",
                type: "WebView",
                path: "Payment.body[0].children[0]",
                name: "WebView",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_s786tzvd",
                type: "Container",
                path: "Payment.body[0].children[1]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Button_fm0z5l15",
                    type: "Button",
                    path: "Payment.body[0].children[1].children[0]",
                    name: "Button",
                    text: "Done — view my order",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

