// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final profileHandle = ffai.ProjectPageHandle<ProfileParams, ProfileState>(
  name: "Profile",
  key: "Scaffold_q2h0gh6v",
  route: "profile",
  params: const ProfileParams(),
  state: const ProfileState(),
  widgets: ProfileWidgets.tree,
);

final class ProfileParams {
  const ProfileParams();
}

final class ProfileState {
  const ProfileState();
  ffai.ProjectStateFieldHandle get me =>
      const ffai.ProjectStateFieldHandle(
        name: "me",
        key: "gef4p2dl",
        typeName: "DataStruct<Profile>",
      );
  ffai.ProjectStateFieldHandle get saving =>
      const ffai.ProjectStateFieldHandle(
        name: "saving",
        key: "5pocwi9u",
        typeName: "Boolean",
      );
}

abstract final class ProfileWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_q2h0gh6v",
      type: "Scaffold",
      path: "Profile",
      name: "Profile",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_84jcfhif",
            type: "AppBar",
            path: "Profile.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_2oh01y4y",
                  type: "Text",
                  path: "Profile.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Profile",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_w9zloefp",
            type: "Column",
            path: "Profile.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_gc86vr77",
                type: "Container",
                path: "Profile.body[0].children[0]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_afnkvq42",
                    type: "Column",
                    path: "Profile.body[0].children[0].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_ydi6qoh8",
                        type: "Text",
                        path: "Profile.body[0].children[0].children[0].children[0]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_kyrhcwcb",
                        type: "Row",
                        path: "Profile.body[0].children[0].children[0].children[1]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_8b66yf8h",
                            type: "Text",
                            path: "Profile.body[0].children[0].children[0].children[1].children[0]",
                            name: "Text",
                            text: "Email",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_w3idirng",
                            type: "Text",
                            path: "Profile.body[0].children[0].children[0].children[1].children[1]",
                            name: "Text",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_co8hrnxj",
                        type: "Row",
                        path: "Profile.body[0].children[0].children[0].children[2]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_8b9f8p2y",
                            type: "Text",
                            path: "Profile.body[0].children[0].children[0].children[2].children[0]",
                            name: "Text",
                            text: "Name",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_ddr1sokb",
                            type: "Text",
                            path: "Profile.body[0].children[0].children[0].children[2].children[1]",
                            name: "Text",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_v9cfq2ns",
                        type: "Row",
                        path: "Profile.body[0].children[0].children[0].children[3]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_zxudto6r",
                            type: "Text",
                            path: "Profile.body[0].children[0].children[0].children[3].children[0]",
                            name: "Text",
                            text: "Phone",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_z25jli91",
                            type: "Text",
                            path: "Profile.body[0].children[0].children[0].children[3].children[1]",
                            name: "Text",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_vlasyqi9",
                        type: "Row",
                        path: "Profile.body[0].children[0].children[0].children[4]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_968lmwi9",
                            type: "Text",
                            path: "Profile.body[0].children[0].children[0].children[4].children[0]",
                            name: "Text",
                            text: "Address",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_a86q9zci",
                            type: "Text",
                            path: "Profile.body[0].children[0].children[0].children[4].children[1]",
                            name: "Text",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_1cl3sn95",
                type: "Text",
                path: "Profile.body[0].children[1]",
                name: "Text",
                text: "Update your details",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_7uiko815",
                type: "Text",
                path: "Profile.body[0].children[2]",
                name: "Text",
                text: "Leave a box empty to keep what you have now.",
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_50bahkms",
                type: "TextField",
                path: "Profile.body[0].children[3]",
                name: "pfName",
                text: "Full name",
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_2zxp30ho",
                type: "TextField",
                path: "Profile.body[0].children[4]",
                name: "pfPhone",
                text: "Mobile number",
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_ehg8revr",
                type: "TextField",
                path: "Profile.body[0].children[5]",
                name: "pfAddress",
                text: "Delivery address",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_9u3guscu",
                type: "Button",
                path: "Profile.body[0].children[6]",
                name: "pfSave",
                text: "Save changes",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_kqc5ooqi",
                type: "Text",
                path: "Profile.body[0].children[7]",
                name: "Text",
                text: "Change password",
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_ehjpiw7s",
                type: "TextField",
                path: "Profile.body[0].children[8]",
                name: "pfCurrent",
                text: "Current password",
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_vz7kxpv2",
                type: "TextField",
                path: "Profile.body[0].children[9]",
                name: "pfNew",
                text: "New password",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_7s53ar74",
                type: "Button",
                path: "Profile.body[0].children[10]",
                name: "pfChangePassword",
                text: "Change password",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

