// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final registerHandle = ffai.ProjectPageHandle<RegisterParams, RegisterState>(
  name: "Register",
  key: "Scaffold_zcbeobxd",
  route: "register",
  params: const RegisterParams(),
  state: const RegisterState(),
  widgets: RegisterWidgets.tree,
);

final class RegisterParams {
  const RegisterParams();
}

final class RegisterState {
  const RegisterState();
  ffai.ProjectStateFieldHandle get busy =>
      const ffai.ProjectStateFieldHandle(
        name: "busy",
        key: "dk1rkgwf",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get email =>
      const ffai.ProjectStateFieldHandle(
        name: "email",
        key: "r3w3znad",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get fullName =>
      const ffai.ProjectStateFieldHandle(
        name: "fullName",
        key: "ppmco8bm",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get password =>
      const ffai.ProjectStateFieldHandle(
        name: "password",
        key: "066vixjj",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get username =>
      const ffai.ProjectStateFieldHandle(
        name: "username",
        key: "rhr86dm4",
        typeName: "String",
      );
}

abstract final class RegisterWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_zcbeobxd",
      type: "Scaffold",
      path: "Register",
      name: "Register",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_4xlfjp0b",
            type: "AppBar",
            path: "Register.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_li2s3983",
                  type: "Text",
                  path: "Register.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Create account",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_febqhbxc",
            type: "Column",
            path: "Register.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Text_vsdlbwya",
                type: "Text",
                path: "Register.body[0].children[0]",
                name: "Text",
                text: "Join SoleCraftPH",
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_pe6yr839",
                type: "TextField",
                path: "Register.body[0].children[1]",
                name: "rgUsername",
                text: "Username",
                triggers: const <String>[
                  "ON_TEXTFIELD_CHANGE",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_p2qn9u1d",
                type: "TextField",
                path: "Register.body[0].children[2]",
                name: "rgFullName",
                text: "Full name",
                triggers: const <String>[
                  "ON_TEXTFIELD_CHANGE",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_2sa1l44m",
                type: "TextField",
                path: "Register.body[0].children[3]",
                name: "rgEmail",
                text: "Email",
                triggers: const <String>[
                  "ON_TEXTFIELD_CHANGE",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_ozrv4ee1",
                type: "TextField",
                path: "Register.body[0].children[4]",
                name: "rgPassword",
                text: "Password",
                triggers: const <String>[
                  "ON_TEXTFIELD_CHANGE",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_epmjm449",
                type: "Button",
                path: "Register.body[0].children[5]",
                name: "Button",
                text: "Create account",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ProgressBar_2kzgl7xq",
                type: "ProgressBar",
                path: "Register.body[0].children[6]",
                name: "ProgressBar",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_styxuh7j",
                type: "Button",
                path: "Register.body[0].children[7]",
                name: "Button",
                text: "Already have an account? Sign in",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

