// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final reviewsHandle = ffai.ProjectPageHandle<ReviewsParams, ReviewsState>(
  name: "Reviews",
  key: "Scaffold_vb7yp4g1",
  route: "reviews",
  params: const ReviewsParams(),
  state: const ReviewsState(),
  widgets: ReviewsWidgets.tree,
);

final class ReviewsParams {
  const ReviewsParams();
  ffai.ProjectParamHandle get productId =>
      const ffai.ProjectParamHandle(
        name: "productId",
        key: "atefhimo",
        typeName: "Integer",
      );
  ffai.ProjectParamHandle get shoeName =>
      const ffai.ProjectParamHandle(
        name: "shoeName",
        key: "mlmvfhuc",
        typeName: "String",
      );
}

final class ReviewsState {
  const ReviewsState();
  ffai.ProjectStateFieldHandle get feed =>
      const ffai.ProjectStateFieldHandle(
        name: "feed",
        key: "6z2wjpuv",
        typeName: "DataStruct<ReviewFeed>",
      );
  ffai.ProjectStateFieldHandle get rating =>
      const ffai.ProjectStateFieldHandle(
        name: "rating",
        key: "dbj7whfp",
        typeName: "Integer",
      );
}

abstract final class ReviewsWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_vb7yp4g1",
      type: "Scaffold",
      path: "Reviews",
      name: "Reviews",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_43dduz6v",
            type: "AppBar",
            path: "Reviews.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_4m6joqx7",
                  type: "Text",
                  path: "Reviews.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Reviews",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_bf2drkwo",
            type: "Column",
            path: "Reviews.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Text_a5uhlslm",
                type: "Text",
                path: "Reviews.body[0].children[0]",
                name: "Text",
              ),
              ffai.ProjectWidgetHandle(
                key: "Row_5xjr2v4i",
                type: "Row",
                path: "Reviews.body[0].children[1]",
                name: "Row",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Icon_f91btlui",
                    type: "Icon",
                    path: "Reviews.body[0].children[1].children[0]",
                    name: "Icon",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_h7a4kt04",
                    type: "Text",
                    path: "Reviews.body[0].children[1].children[1]",
                    name: "Text",
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_qpiyafiw",
                type: "Container",
                path: "Reviews.body[0].children[2]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_h81ory95",
                    type: "Column",
                    path: "Reviews.body[0].children[2].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_pwgo3v5h",
                        type: "Text",
                        path: "Reviews.body[0].children[2].children[0].children[0]",
                        name: "Text",
                        text: "Write a review",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Column_h35q532o",
                        type: "Column",
                        path: "Reviews.body[0].children[2].children[0].children[1]",
                        name: "starPicker",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_n4z2jmhn",
                            type: "Row",
                            path: "Reviews.body[0].children[2].children[0].children[1].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "IconButton_l9wrdrfk",
                                type: "IconButton",
                                path: "Reviews.body[0].children[2].children[0].children[1].children[0].children[0]",
                                name: "starOn1",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "IconButton_mhtyge46",
                                type: "IconButton",
                                path: "Reviews.body[0].children[2].children[0].children[1].children[0].children[1]",
                                name: "starOff1",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "IconButton_8dmxdt5h",
                                type: "IconButton",
                                path: "Reviews.body[0].children[2].children[0].children[1].children[0].children[2]",
                                name: "starOn2",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "IconButton_dickoxax",
                                type: "IconButton",
                                path: "Reviews.body[0].children[2].children[0].children[1].children[0].children[3]",
                                name: "starOff2",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "IconButton_m1twrzgd",
                                type: "IconButton",
                                path: "Reviews.body[0].children[2].children[0].children[1].children[0].children[4]",
                                name: "starOn3",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "IconButton_pwpvgolm",
                                type: "IconButton",
                                path: "Reviews.body[0].children[2].children[0].children[1].children[0].children[5]",
                                name: "starOff3",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "IconButton_6zawo07u",
                                type: "IconButton",
                                path: "Reviews.body[0].children[2].children[0].children[1].children[0].children[6]",
                                name: "starOn4",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "IconButton_453aqd77",
                                type: "IconButton",
                                path: "Reviews.body[0].children[2].children[0].children[1].children[0].children[7]",
                                name: "starOff4",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "IconButton_x1mau4wb",
                                type: "IconButton",
                                path: "Reviews.body[0].children[2].children[0].children[1].children[0].children[8]",
                                name: "starOn5",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "IconButton_knvq53bd",
                                type: "IconButton",
                                path: "Reviews.body[0].children[2].children[0].children[1].children[0].children[9]",
                                name: "starOff5",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_qby1te3c",
                            type: "Text",
                            path: "Reviews.body[0].children[2].children[0].children[1].children[1]",
                            name: "Text",
                            text: "Tap a star to rate",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "TextField_ft7j44h0",
                        type: "TextField",
                        path: "Reviews.body[0].children[2].children[0].children[2]",
                        name: "reviewComment",
                        text: "Your review",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_vkftj6ac",
                        type: "Button",
                        path: "Reviews.body[0].children[2].children[0].children[3]",
                        name: "postReview",
                        text: "Post review",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_u0669urt",
                type: "Text",
                path: "Reviews.body[0].children[3]",
                name: "reviewsLocked",
                text: "You can review this shoe once you have ordered it.",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_vso3tkot",
                type: "Text",
                path: "Reviews.body[0].children[4]",
                name: "reviewsDone",
                text: "You have already reviewed this shoe.",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_uk2y7i34",
                type: "Text",
                path: "Reviews.body[0].children[5]",
                name: "reviewsEmpty",
                text: "No reviews yet.",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_guswn7fv",
                type: "ListView",
                path: "Reviews.body[0].children[6]",
                name: "ListView",
                triggers: const <String>[
                  "ON_PULL_TO_REFRESH",
                ],
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_8nn8rzoo",
                    type: "Container",
                    path: "Reviews.body[0].children[6].children[0]",
                    name: "Container",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_7hp4i5d3",
                        type: "Column",
                        path: "Reviews.body[0].children[6].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_1zvgufkj",
                            type: "Row",
                            path: "Reviews.body[0].children[6].children[0].children[0].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_dwjq2og6",
                                type: "Text",
                                path: "Reviews.body[0].children[6].children[0].children[0].children[0].children[0]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_j39yewdf",
                                type: "Row",
                                path: "Reviews.body[0].children[6].children[0].children[0].children[0].children[1]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_mjrctb53",
                                    type: "Icon",
                                    path: "Reviews.body[0].children[6].children[0].children[0].children[0].children[1].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_5ni0tski",
                                    type: "Text",
                                    path: "Reviews.body[0].children[6].children[0].children[0].children[0].children[1].children[1]",
                                    name: "Text",
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_2if838ql",
                            type: "Text",
                            path: "Reviews.body[0].children[6].children[0].children[0].children[1]",
                            name: "Text",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_ku74nq2z",
                            type: "Text",
                            path: "Reviews.body[0].children[6].children[0].children[0].children[2]",
                            name: "Text",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

