// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final shopHandle = ffai.ProjectPageHandle<ShopParams, ShopState>(
  name: "Shop",
  key: "Scaffold_5f5fk831",
  route: "shop",
  params: const ShopParams(),
  state: const ShopState(),
  widgets: ShopWidgets.tree,
);

final class ShopParams {
  const ShopParams();
}

final class ShopState {
  const ShopState();
  ffai.ProjectStateFieldHandle get activeCategory =>
      const ffai.ProjectStateFieldHandle(
        name: "activeCategory",
        key: "kjggwo3p",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get isLoading =>
      const ffai.ProjectStateFieldHandle(
        name: "isLoading",
        key: "b7y968ww",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get search =>
      const ffai.ProjectStateFieldHandle(
        name: "search",
        key: "2cr196mp",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get shoes =>
      const ffai.ProjectStateFieldHandle(
        name: "shoes",
        key: "vzjm24w8",
        typeName: "List<DataStruct<Shoe>>",
      );
}

abstract final class ShopWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_5f5fk831",
      type: "Scaffold",
      path: "Shop",
      name: "Shop",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_sn4w8jjj",
            type: "AppBar",
            path: "Shop.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_ustunjwv",
                  type: "Text",
                  path: "Shop.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "SoleCraftPH",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_yqy58ysf",
            type: "Column",
            path: "Shop.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_dlxwv3w5",
                type: "Container",
                path: "Shop.body[0].children[0]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_2vfp818e",
                    type: "Row",
                    path: "Shop.body[0].children[0].children[0]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "TextField_tqobar4t",
                        type: "TextField",
                        path: "Shop.body[0].children[0].children[0].children[0]",
                        name: "shopSearchField",
                        text: "Search shoes, brands…",
                        triggers: const <String>[
                          "ON_TEXTFIELD_CHANGE",
                          "ON_TEXTFIELD_SUBMIT",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Badge_2p67vz3b",
                        type: "Badge",
                        path: "Shop.body[0].children[0].children[0].children[1]",
                        name: "Badge",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "IconButton_tn1w4uvk",
                            type: "IconButton",
                            path: "Shop.body[0].children[0].children[0].children[1].children[0]",
                            name: "IconButton",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_w56b0wzf",
                type: "Container",
                path: "Shop.body[0].children[1]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_d7cz6r2b",
                    type: "Row",
                    path: "Shop.body[0].children[1].children[0]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_xfqqjoas",
                        type: "Container",
                        path: "Shop.body[0].children[1].children[0].children[0]",
                        name: "ChipAll",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_8erwrjqe",
                            type: "Container",
                            path: "Shop.body[0].children[1].children[0].children[0].children[0]",
                            name: "CatChip",
                            componentName: "CatChip",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_k7rad63w",
                        type: "Container",
                        path: "Shop.body[0].children[1].children[0].children[1]",
                        name: "ChipPerformance",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_mechbqbg",
                            type: "Container",
                            path: "Shop.body[0].children[1].children[0].children[1].children[0]",
                            name: "CatChip",
                            componentName: "CatChip",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_nkjt8umr",
                        type: "Container",
                        path: "Shop.body[0].children[1].children[0].children[2]",
                        name: "ChipCasual",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_k7du1md0",
                            type: "Container",
                            path: "Shop.body[0].children[1].children[0].children[2].children[0]",
                            name: "CatChip",
                            componentName: "CatChip",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_tppnzt06",
                        type: "Container",
                        path: "Shop.body[0].children[1].children[0].children[3]",
                        name: "ChipFormal",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_tg0tmr2s",
                            type: "Container",
                            path: "Shop.body[0].children[1].children[0].children[3].children[0]",
                            name: "CatChip",
                            componentName: "CatChip",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ProgressBar_yj0p01nu",
                type: "ProgressBar",
                path: "Shop.body[0].children[2]",
                name: "ProgressBar",
              ),
              ffai.ProjectWidgetHandle(
                key: "GridView_ilvt3kls",
                type: "GridView",
                path: "Shop.body[0].children[3]",
                name: "GridView",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_vzkzbk79",
                    type: "Container",
                    path: "Shop.body[0].children[3].children[0]",
                    name: "ShoeCardTap",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_er1fj8un",
                        type: "Container",
                        path: "Shop.body[0].children[3].children[0].children[0]",
                        name: "ShoeCard",
                        componentName: "ShoeCard",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

