// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final signInHandle = ffai.ProjectPageHandle<SignInParams, SignInState>(
  name: "SignIn",
  key: "Scaffold_3r0yfqjf",
  route: "sign-in",
  params: const SignInParams(),
  state: const SignInState(),
  widgets: SignInWidgets.tree,
);

final class SignInParams {
  const SignInParams();
}

final class SignInState {
  const SignInState();
  ffai.ProjectStateFieldHandle get busy =>
      const ffai.ProjectStateFieldHandle(
        name: "busy",
        key: "7vogpr0t",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get login =>
      const ffai.ProjectStateFieldHandle(
        name: "login",
        key: "vg2hkhvi",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get password =>
      const ffai.ProjectStateFieldHandle(
        name: "password",
        key: "e9vovkbl",
        typeName: "String",
      );
}

abstract final class SignInWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_3r0yfqjf",
      type: "Scaffold",
      path: "SignIn",
      name: "SignIn",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_5w89krsq",
            type: "AppBar",
            path: "SignIn.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_pgshb0xh",
                  type: "Text",
                  path: "SignIn.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Sign in",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_k1pmej7x",
            type: "Column",
            path: "SignIn.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Text_xxh6x5pj",
                type: "Text",
                path: "SignIn.body[0].children[0]",
                name: "Text",
                text: "Welcome back",
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_i7r0nq3x",
                type: "Text",
                path: "SignIn.body[0].children[1]",
                name: "Text",
                text: "Use the same username or email as the SoleCraftPH website.",
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_muqavw4s",
                type: "TextField",
                path: "SignIn.body[0].children[2]",
                name: "siLogin",
                text: "Username or email",
                triggers: const <String>[
                  "ON_TEXTFIELD_CHANGE",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "TextField_d3wwv68m",
                type: "TextField",
                path: "SignIn.body[0].children[3]",
                name: "siPassword",
                text: "Password",
                triggers: const <String>[
                  "ON_TEXTFIELD_CHANGE",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_sv4216kt",
                type: "Button",
                path: "SignIn.body[0].children[4]",
                name: "Button",
                text: "Sign in",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ProgressBar_4xx538ti",
                type: "ProgressBar",
                path: "SignIn.body[0].children[5]",
                name: "ProgressBar",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_f6bwzfs0",
                type: "Button",
                path: "SignIn.body[0].children[6]",
                name: "Button",
                text: "New here? Create an account",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

