// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final wishlistHandle = ffai.ProjectPageHandle<WishlistParams, WishlistState>(
  name: "Wishlist",
  key: "Scaffold_29qqsl1k",
  route: "wishlist",
  params: const WishlistParams(),
  state: const WishlistState(),
  widgets: WishlistWidgets.tree,
);

final class WishlistParams {
  const WishlistParams();
}

final class WishlistState {
  const WishlistState();
  ffai.ProjectStateFieldHandle get saved =>
      const ffai.ProjectStateFieldHandle(
        name: "saved",
        key: "fcfgks5i",
        typeName: "DataStruct<Wishlist>",
      );
}

abstract final class WishlistWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_29qqsl1k",
      type: "Scaffold",
      path: "Wishlist",
      name: "Wishlist",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_skhkjp0n",
            type: "AppBar",
            path: "Wishlist.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_vwfwu96m",
                  type: "Text",
                  path: "Wishlist.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Wishlist",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_tb8lpkjw",
            type: "Column",
            path: "Wishlist.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Text_b7bq9aos",
                type: "Text",
                path: "Wishlist.body[0].children[0]",
                name: "wishlistEmpty",
                text: "Nothing saved yet. Tap the heart on any shoe to keep it here.",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_hmc891ud",
                type: "ListView",
                path: "Wishlist.body[0].children[1]",
                name: "ListView",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_wgyw1nt1",
                    type: "Container",
                    path: "Wishlist.body[0].children[1].children[0]",
                    name: "Container",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_m0coa2fo",
                        type: "Row",
                        path: "Wishlist.body[0].children[1].children[0].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Image_kx6yqtao",
                            type: "Image",
                            path: "Wishlist.body[0].children[1].children[0].children[0].children[0]",
                            name: "Image",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Column_3sfxh85m",
                            type: "Column",
                            path: "Wishlist.body[0].children[1].children[0].children[0].children[1]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_z0jqexng",
                                type: "Text",
                                path: "Wishlist.body[0].children[1].children[0].children[0].children[1].children[0]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_197iz35r",
                                type: "Text",
                                path: "Wishlist.body[0].children[1].children[0].children[0].children[1].children[1]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_lvlov5sf",
                                type: "Text",
                                path: "Wishlist.body[0].children[1].children[0].children[0].children[1].children[2]",
                                name: "Text",
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

