// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final cartPageHandle = ffai.ProjectPageHandle<CartPageParams, CartPageState>(
  name: "CartPage",
  key: "Scaffold_ar6lfnql",
  route: "cart",
  params: const CartPageParams(),
  state: const CartPageState(),
  widgets: CartPageWidgets.tree,
);

final class CartPageParams {
  const CartPageParams();
}

final class CartPageState {
  const CartPageState();
}

abstract final class CartPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_ar6lfnql",
      type: "Scaffold",
      path: "CartPage",
      name: "CartPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_g9tm7sax",
            type: "AppBar",
            path: "CartPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_69ducpul",
                  type: "Text",
                  path: "CartPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Cart",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_2ajvrint",
            type: "Container",
            path: "CartPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_3w0wmnf3",
                type: "Column",
                path: "CartPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "ListView_bgdp37ia",
                    type: "ListView",
                    path: "CartPage.body[0].children[0].children[0]",
                    name: "ListView",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_nh7dnm76",
                        type: "Container",
                        path: "CartPage.body[0].children[0].children[0].children[0]",
                        name: "Container",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_jv3pwmjz",
                            type: "Row",
                            path: "CartPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Image_rvi31tw7",
                                type: "Image",
                                path: "CartPage.body[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "Image",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Column_0ewqvjyu",
                                type: "Column",
                                path: "CartPage.body[0].children[0].children[0].children[0].children[0].children[1]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_l0b0vt0s",
                                    type: "Text",
                                    path: "CartPage.body[0].children[0].children[0].children[0].children[0].children[1].children[0]",
                                    name: "Text",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_bhpqeju7",
                                    type: "Row",
                                    path: "CartPage.body[0].children[0].children[0].children[0].children[0].children[1].children[1]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_y9m3hn2w",
                                        type: "Text",
                                        path: "CartPage.body[0].children[0].children[0].children[0].children[0].children[1].children[1].children[0]",
                                        name: "Text",
                                        text: "₱",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_4nfk3c1i",
                                        type: "Text",
                                        path: "CartPage.body[0].children[0].children[0].children[0].children[0].children[1].children[1].children[1]",
                                        name: "Text",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_whqfdsgu",
                                type: "Row",
                                path: "CartPage.body[0].children[0].children[0].children[0].children[0].children[2]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_jffdz4ru",
                                    type: "Text",
                                    path: "CartPage.body[0].children[0].children[0].children[0].children[0].children[2].children[0]",
                                    name: "Text",
                                    text: "Qty",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_825xydcc",
                                    type: "Text",
                                    path: "CartPage.body[0].children[0].children[0].children[0].children[0].children[2].children[1]",
                                    name: "Text",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "IconButton_tw6g5lh9",
                                type: "IconButton",
                                path: "CartPage.body[0].children[0].children[0].children[0].children[0].children[3]",
                                name: "IconButton",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_4q1pnfri",
                    type: "Button",
                    path: "CartPage.body[0].children[0].children[1]",
                    name: "Button",
                    text: "Proceed to Checkout",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

