// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final checkoutPageHandle = ffai.ProjectPageHandle<CheckoutPageParams, CheckoutPageState>(
  name: "CheckoutPage",
  key: "Scaffold_dh46lpg8",
  route: "checkout",
  params: const CheckoutPageParams(),
  state: const CheckoutPageState(),
  widgets: CheckoutPageWidgets.tree,
);

final class CheckoutPageParams {
  const CheckoutPageParams();
}

final class CheckoutPageState {
  const CheckoutPageState();
  ffai.ProjectStateFieldHandle get address =>
      const ffai.ProjectStateFieldHandle(
        name: "address",
        key: "kdmcm0vx",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get email =>
      const ffai.ProjectStateFieldHandle(
        name: "email",
        key: "m21fucg1",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get name =>
      const ffai.ProjectStateFieldHandle(
        name: "name",
        key: "zm3ylxgh",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get paymentMethod =>
      const ffai.ProjectStateFieldHandle(
        name: "paymentMethod",
        key: "xrbn90om",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get phone =>
      const ffai.ProjectStateFieldHandle(
        name: "phone",
        key: "9f91yh6j",
        typeName: "String",
      );
}

abstract final class CheckoutPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_dh46lpg8",
      type: "Scaffold",
      path: "CheckoutPage",
      name: "CheckoutPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_vc49u76i",
            type: "AppBar",
            path: "CheckoutPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_5t76i3pi",
                  type: "Text",
                  path: "CheckoutPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Checkout",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_cd7d0h7v",
            type: "Container",
            path: "CheckoutPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_sbvlnw44",
                type: "Column",
                path: "CheckoutPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_o4kdkx26",
                    type: "Text",
                    path: "CheckoutPage.body[0].children[0].children[0]",
                    name: "Text",
                    text: "Shipping details",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_6anr7rvq",
                    type: "TextField",
                    path: "CheckoutPage.body[0].children[0].children[1]",
                    name: "TextField",
                    text: "Full Name",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_t9ojcs1s",
                    type: "TextField",
                    path: "CheckoutPage.body[0].children[0].children[2]",
                    name: "TextField",
                    text: "Email",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_slhllayt",
                    type: "TextField",
                    path: "CheckoutPage.body[0].children[0].children[3]",
                    name: "TextField",
                    text: "Phone",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_que821id",
                    type: "TextField",
                    path: "CheckoutPage.body[0].children[0].children[4]",
                    name: "TextField",
                    text: "Address",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_aemkr2yx",
                    type: "Text",
                    path: "CheckoutPage.body[0].children[0].children[5]",
                    name: "Text",
                    text: "Payment method",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Row_67f9h03o",
                    type: "Row",
                    path: "CheckoutPage.body[0].children[0].children[6]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Button_x0vgd6f4",
                        type: "Button",
                        path: "CheckoutPage.body[0].children[0].children[6].children[0]",
                        name: "Button",
                        text: "COD",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_lqiaknc9",
                        type: "Button",
                        path: "CheckoutPage.body[0].children[0].children[6].children[1]",
                        name: "Button",
                        text: "GCASH",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_2bx2se4q",
                        type: "Button",
                        path: "CheckoutPage.body[0].children[0].children[6].children[2]",
                        name: "Button",
                        text: "CARD",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Row_ax6pnzsr",
                    type: "Row",
                    path: "CheckoutPage.body[0].children[0].children[7]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_bzyh2ao3",
                        type: "Text",
                        path: "CheckoutPage.body[0].children[0].children[7].children[0]",
                        name: "Text",
                        text: "Selected:",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_jsjdfwf0",
                        type: "Text",
                        path: "CheckoutPage.body[0].children[0].children[7].children[1]",
                        name: "Text",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_3yzme7ef",
                    type: "Button",
                    path: "CheckoutPage.body[0].children[0].children[8]",
                    name: "Button",
                    text: "Place Order",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

