// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final loginPageHandle = ffai.ProjectPageHandle<LoginPageParams, LoginPageState>(
  name: "LoginPage",
  key: "Scaffold_f6x72m2v",
  route: "login",
  params: const LoginPageParams(),
  state: const LoginPageState(),
  widgets: LoginPageWidgets.tree,
);

final class LoginPageParams {
  const LoginPageParams();
}

final class LoginPageState {
  const LoginPageState();
  ffai.ProjectStateFieldHandle get busy =>
      const ffai.ProjectStateFieldHandle(
        name: "busy",
        key: "0ocl0dbp",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get login =>
      const ffai.ProjectStateFieldHandle(
        name: "login",
        key: "g1rm56qf",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get password =>
      const ffai.ProjectStateFieldHandle(
        name: "password",
        key: "ca4c7w2q",
        typeName: "String",
      );
}

abstract final class LoginPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_f6x72m2v",
      type: "Scaffold",
      path: "LoginPage",
      name: "LoginPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_kbt09irn",
            type: "AppBar",
            path: "LoginPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_c92ipg11",
                  type: "Text",
                  path: "LoginPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Sign In",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_w18tx7c0",
            type: "Container",
            path: "LoginPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_5tzwloer",
                type: "Column",
                path: "LoginPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_5g32l691",
                    type: "Text",
                    path: "LoginPage.body[0].children[0].children[0]",
                    name: "Text",
                    text: "Welcome back",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_da0mvyqr",
                    type: "TextField",
                    path: "LoginPage.body[0].children[0].children[1]",
                    name: "loginField",
                    text: "Email or Username",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_g6z89sg9",
                    type: "TextField",
                    path: "LoginPage.body[0].children[0].children[2]",
                    name: "passwordField",
                    text: "Password",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_axei8snj",
                    type: "Button",
                    path: "LoginPage.body[0].children[0].children[3]",
                    name: "Button",
                    text: "Sign In",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_roobwbga",
                    type: "Button",
                    path: "LoginPage.body[0].children[0].children[4]",
                    name: "Button",
                    text: "Create an account",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

