// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final ordersPageHandle = ffai.ProjectPageHandle<OrdersPageParams, OrdersPageState>(
  name: "OrdersPage",
  key: "Scaffold_6tpy91gg",
  route: "orders",
  params: const OrdersPageParams(),
  state: const OrdersPageState(),
  widgets: OrdersPageWidgets.tree,
);

final class OrdersPageParams {
  const OrdersPageParams();
}

final class OrdersPageState {
  const OrdersPageState();
  ffai.ProjectStateFieldHandle get loading =>
      const ffai.ProjectStateFieldHandle(
        name: "loading",
        key: "f16qder9",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get orders =>
      const ffai.ProjectStateFieldHandle(
        name: "orders",
        key: "29dsjuob",
        typeName: "List<DataStruct<OrderSummary>>",
      );
}

abstract final class OrdersPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_6tpy91gg",
      type: "Scaffold",
      path: "OrdersPage",
      name: "OrdersPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_hmicfhm7",
            type: "AppBar",
            path: "OrdersPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_6buk3rtu",
                  type: "Text",
                  path: "OrdersPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "My Orders",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_hn0cfbkw",
            type: "Container",
            path: "OrdersPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_5bos9oez",
                type: "Column",
                path: "OrdersPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_p5p3n2xi",
                    type: "ProgressBar",
                    path: "OrdersPage.body[0].children[0].children[0]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListView_o0tcsxo7",
                    type: "ListView",
                    path: "OrdersPage.body[0].children[0].children[1]",
                    name: "ListView",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_awkrlzel",
                        type: "Container",
                        path: "OrdersPage.body[0].children[0].children[1].children[0]",
                        name: "Container",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_rzqaj1u9",
                            type: "Row",
                            path: "OrdersPage.body[0].children[0].children[1].children[0].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_6n14zyks",
                                type: "Column",
                                path: "OrdersPage.body[0].children[0].children[1].children[0].children[0].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_v1ox89ef",
                                    type: "Row",
                                    path: "OrdersPage.body[0].children[0].children[1].children[0].children[0].children[0].children[0]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_s5hjhds1",
                                        type: "Text",
                                        path: "OrdersPage.body[0].children[0].children[1].children[0].children[0].children[0].children[0].children[0]",
                                        name: "Text",
                                        text: "Order #",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_cwsnmirz",
                                        type: "Text",
                                        path: "OrdersPage.body[0].children[0].children[1].children[0].children[0].children[0].children[0].children[1]",
                                        name: "Text",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_odk1ooom",
                                    type: "Text",
                                    path: "OrdersPage.body[0].children[0].children[1].children[0].children[0].children[0].children[1]",
                                    name: "Text",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_akndaftp",
                                type: "Row",
                                path: "OrdersPage.body[0].children[0].children[1].children[0].children[0].children[1]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_0e1r8tr8",
                                    type: "Text",
                                    path: "OrdersPage.body[0].children[0].children[1].children[0].children[0].children[1].children[0]",
                                    name: "Text",
                                    text: "₱",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_y1vg4gu7",
                                    type: "Text",
                                    path: "OrdersPage.body[0].children[0].children[1].children[0].children[0].children[1].children[1]",
                                    name: "Text",
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

