// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final orderDetailPageHandle = ffai.ProjectPageHandle<OrderDetailPageParams, OrderDetailPageState>(
  name: "OrderDetailPage",
  key: "Scaffold_h565y3py",
  route: "order-detail",
  params: const OrderDetailPageParams(),
  state: const OrderDetailPageState(),
  widgets: OrderDetailPageWidgets.tree,
);

final class OrderDetailPageParams {
  const OrderDetailPageParams();
  ffai.ProjectParamHandle get orderId =>
      const ffai.ProjectParamHandle(
        name: "orderId",
        key: "8xk3ag2k",
        typeName: "Integer",
      );
}

final class OrderDetailPageState {
  const OrderDetailPageState();
  ffai.ProjectStateFieldHandle get items =>
      const ffai.ProjectStateFieldHandle(
        name: "items",
        key: "4qhkajxo",
        typeName: "List<DataStruct<OrderItem>>",
      );
  ffai.ProjectStateFieldHandle get status =>
      const ffai.ProjectStateFieldHandle(
        name: "status",
        key: "o6kbi8sj",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get timeline =>
      const ffai.ProjectStateFieldHandle(
        name: "timeline",
        key: "k6u0y5ph",
        typeName: "List<DataStruct<StatusLog>>",
      );
  ffai.ProjectStateFieldHandle get total =>
      const ffai.ProjectStateFieldHandle(
        name: "total",
        key: "xnvzgmuj",
        typeName: "Double",
      );
}

abstract final class OrderDetailPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_h565y3py",
      type: "Scaffold",
      path: "OrderDetailPage",
      name: "OrderDetailPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_pouq6bcb",
            type: "AppBar",
            path: "OrderDetailPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_oxkrahno",
                  type: "Text",
                  path: "OrderDetailPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Order Detail",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_01qdpyd5",
            type: "Container",
            path: "OrderDetailPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_u76ijyqt",
                type: "Column",
                path: "OrderDetailPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_b6zmztbk",
                    type: "Row",
                    path: "OrderDetailPage.body[0].children[0].children[0]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_cl0ydidt",
                        type: "Text",
                        path: "OrderDetailPage.body[0].children[0].children[0].children[0]",
                        name: "Text",
                        text: "Status:",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_fr1wpxou",
                        type: "Text",
                        path: "OrderDetailPage.body[0].children[0].children[0].children[1]",
                        name: "Text",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_h68yndrq",
                    type: "Text",
                    path: "OrderDetailPage.body[0].children[0].children[1]",
                    name: "Text",
                    text: "Items",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListView_ybcffhgw",
                    type: "ListView",
                    path: "OrderDetailPage.body[0].children[0].children[2]",
                    name: "ListView",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_issjds33",
                        type: "Container",
                        path: "OrderDetailPage.body[0].children[0].children[2].children[0]",
                        name: "Container",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_5l1i527y",
                            type: "Row",
                            path: "OrderDetailPage.body[0].children[0].children[2].children[0].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_j7pdbkxh",
                                type: "Text",
                                path: "OrderDetailPage.body[0].children[0].children[2].children[0].children[0].children[0]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_n3xp691a",
                                type: "Text",
                                path: "OrderDetailPage.body[0].children[0].children[2].children[0].children[0].children[1]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_s5pduejz",
                                type: "Row",
                                path: "OrderDetailPage.body[0].children[0].children[2].children[0].children[0].children[2]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_mzorg9gp",
                                    type: "Text",
                                    path: "OrderDetailPage.body[0].children[0].children[2].children[0].children[0].children[2].children[0]",
                                    name: "Text",
                                    text: "₱",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_4xbt4wkk",
                                    type: "Text",
                                    path: "OrderDetailPage.body[0].children[0].children[2].children[0].children[0].children[2].children[1]",
                                    name: "Text",
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Divider_e0l1rbtr",
                    type: "Divider",
                    path: "OrderDetailPage.body[0].children[0].children[3]",
                    name: "Divider",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_p8g5cxuq",
                    type: "Text",
                    path: "OrderDetailPage.body[0].children[0].children[4]",
                    name: "Text",
                    text: "Timeline",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListView_vmu6vf6c",
                    type: "ListView",
                    path: "OrderDetailPage.body[0].children[0].children[5]",
                    name: "ListView",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_iwvpsmwi",
                        type: "Row",
                        path: "OrderDetailPage.body[0].children[0].children[5].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_tk7a1qe5",
                            type: "Icon",
                            path: "OrderDetailPage.body[0].children[0].children[5].children[0].children[0]",
                            name: "Icon",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Column_ivg0e7wb",
                            type: "Column",
                            path: "OrderDetailPage.body[0].children[0].children[5].children[0].children[1]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_7meekif5",
                                type: "Text",
                                path: "OrderDetailPage.body[0].children[0].children[5].children[0].children[1].children[0]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_885m8n96",
                                type: "Text",
                                path: "OrderDetailPage.body[0].children[0].children[5].children[0].children[1].children[1]",
                                name: "Text",
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

