// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final orderConfirmationPageHandle = ffai.ProjectPageHandle<OrderConfirmationPageParams, OrderConfirmationPageState>(
  name: "OrderConfirmationPage",
  key: "Scaffold_5uxvyhm2",
  route: "order-confirmation",
  params: const OrderConfirmationPageParams(),
  state: const OrderConfirmationPageState(),
  widgets: OrderConfirmationPageWidgets.tree,
);

final class OrderConfirmationPageParams {
  const OrderConfirmationPageParams();
  ffai.ProjectParamHandle get orderId =>
      const ffai.ProjectParamHandle(
        name: "orderId",
        key: "u7u1bt8x",
        typeName: "Integer",
      );
}

final class OrderConfirmationPageState {
  const OrderConfirmationPageState();
}

abstract final class OrderConfirmationPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_5uxvyhm2",
      type: "Scaffold",
      path: "OrderConfirmationPage",
      name: "OrderConfirmationPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_j19bodyo",
            type: "Container",
            path: "OrderConfirmationPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_ctc0e4k6",
                type: "Column",
                path: "OrderConfirmationPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Icon_0rbtfy1j",
                    type: "Icon",
                    path: "OrderConfirmationPage.body[0].children[0].children[0]",
                    name: "Icon",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_2uxms07v",
                    type: "Text",
                    path: "OrderConfirmationPage.body[0].children[0].children[1]",
                    name: "Text",
                    text: "Order placed!",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Row_rlrym2rr",
                    type: "Row",
                    path: "OrderConfirmationPage.body[0].children[0].children[2]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_61onj3g8",
                        type: "Text",
                        path: "OrderConfirmationPage.body[0].children[0].children[2].children[0]",
                        name: "Text",
                        text: "Order #",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_85cpwgv7",
                        type: "Text",
                        path: "OrderConfirmationPage.body[0].children[0].children[2].children[1]",
                        name: "Text",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_1nc5ny0a",
                    type: "Button",
                    path: "OrderConfirmationPage.body[0].children[0].children[3]",
                    name: "Button",
                    text: "View My Orders",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_a31oy768",
                    type: "Button",
                    path: "OrderConfirmationPage.body[0].children[0].children[4]",
                    name: "Button",
                    text: "Continue Shopping",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

