// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final productDetailPageHandle = ffai.ProjectPageHandle<ProductDetailPageParams, ProductDetailPageState>(
  name: "ProductDetailPage",
  key: "Scaffold_kwf8a4ev",
  route: "product",
  params: const ProductDetailPageParams(),
  state: const ProductDetailPageState(),
  widgets: ProductDetailPageWidgets.tree,
);

final class ProductDetailPageParams {
  const ProductDetailPageParams();
  ffai.ProjectParamHandle get productId =>
      const ffai.ProjectParamHandle(
        name: "productId",
        key: "1kykjtx2",
        typeName: "Integer",
      );
}

final class ProductDetailPageState {
  const ProductDetailPageState();
  ffai.ProjectStateFieldHandle get loading =>
      const ffai.ProjectStateFieldHandle(
        name: "loading",
        key: "8fyo62ra",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get product =>
      const ffai.ProjectStateFieldHandle(
        name: "product",
        key: "60zzvq6a",
        typeName: "DataStruct<Product>",
      );
  ffai.ProjectStateFieldHandle get reviewComment =>
      const ffai.ProjectStateFieldHandle(
        name: "reviewComment",
        key: "jxypkaab",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get reviewRating =>
      const ffai.ProjectStateFieldHandle(
        name: "reviewRating",
        key: "dadu0oci",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get reviews =>
      const ffai.ProjectStateFieldHandle(
        name: "reviews",
        key: "2yguzdzp",
        typeName: "List<DataStruct<Review>>",
      );
}

abstract final class ProductDetailPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_kwf8a4ev",
      type: "Scaffold",
      path: "ProductDetailPage",
      name: "ProductDetailPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_qggi8gz5",
            type: "AppBar",
            path: "ProductDetailPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_87smu5mf",
                  type: "Text",
                  path: "ProductDetailPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Details",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_5eav1n38",
            type: "Container",
            path: "ProductDetailPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_pu0sck3p",
                type: "Column",
                path: "ProductDetailPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Image_qjovquhr",
                    type: "Image",
                    path: "ProductDetailPage.body[0].children[0].children[0]",
                    name: "Image",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_wjstpsti",
                    type: "Container",
                    path: "ProductDetailPage.body[0].children[0].children[1]",
                    name: "Container",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_omhigdlz",
                        type: "Column",
                        path: "ProductDetailPage.body[0].children[0].children[1].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_80y63tc5",
                            type: "Text",
                            path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[0]",
                            name: "Text",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Row_55mi4dl1",
                            type: "Row",
                            path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[1]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_7deur6mj",
                                type: "Text",
                                path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[1].children[0]",
                                name: "Text",
                                text: "₱",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_te77lk9x",
                                type: "Text",
                                path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[1].children[1]",
                                name: "Text",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_qqogp8dp",
                            type: "Text",
                            path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[2]",
                            name: "Text",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Row_3xxkwuz9",
                            type: "Row",
                            path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[3]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Button_kh3bia1g",
                                type: "Button",
                                path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[3].children[0]",
                                name: "Button",
                                text: "Add to Cart",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "IconButton_30vz0tz8",
                                type: "IconButton",
                                path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[3].children[1]",
                                name: "IconButton",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Divider_0dwpgpvx",
                            type: "Divider",
                            path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[4]",
                            name: "Divider",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_3u5pbjrb",
                            type: "Text",
                            path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[5]",
                            name: "Text",
                            text: "Reviews",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "ListView_px6nb94w",
                            type: "ListView",
                            path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[6]",
                            name: "ListView",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_k3mqiz0j",
                                type: "Container",
                                path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[6].children[0]",
                                name: "Container",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_fmjcifzr",
                                    type: "Column",
                                    path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[6].children[0].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_f5ch4t7n",
                                        type: "Row",
                                        path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[6].children[0].children[0].children[0]",
                                        name: "Row",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_i36w4lv9",
                                            type: "Icon",
                                            path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[6].children[0].children[0].children[0].children[0]",
                                            name: "Icon",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_nxmezq2t",
                                            type: "Text",
                                            path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[6].children[0].children[0].children[0].children[1]",
                                            name: "Text",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_7xj14gqg",
                                            type: "Text",
                                            path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[6].children[0].children[0].children[0].children[2]",
                                            name: "Text",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_qnbuhpxv",
                                        type: "Text",
                                        path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[6].children[0].children[0].children[1]",
                                        name: "Text",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Divider_w8uqz2ee",
                            type: "Divider",
                            path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[7]",
                            name: "Divider",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_x6ivjqxt",
                            type: "Text",
                            path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[8]",
                            name: "Text",
                            text: "Write a review",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "TextField_as7xee81",
                            type: "TextField",
                            path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[9]",
                            name: "TextField",
                            text: "Rating (1-5)",
                            triggers: const <String>[
                              "ON_TEXTFIELD_CHANGE",
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "TextField_3uj0d220",
                            type: "TextField",
                            path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[10]",
                            name: "TextField",
                            text: "Comment",
                            triggers: const <String>[
                              "ON_TEXTFIELD_CHANGE",
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Button_lshfwmjo",
                            type: "Button",
                            path: "ProductDetailPage.body[0].children[0].children[1].children[0].children[11]",
                            name: "Button",
                            text: "Submit Review",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

