// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final profilePageHandle = ffai.ProjectPageHandle<ProfilePageParams, ProfilePageState>(
  name: "ProfilePage",
  key: "Scaffold_958jo4s6",
  route: "profile",
  params: const ProfilePageParams(),
  state: const ProfilePageState(),
  widgets: ProfilePageWidgets.tree,
);

final class ProfilePageParams {
  const ProfilePageParams();
}

final class ProfilePageState {
  const ProfilePageState();
  ffai.ProjectStateFieldHandle get address =>
      const ffai.ProjectStateFieldHandle(
        name: "address",
        key: "ae56mnb4",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get fullName =>
      const ffai.ProjectStateFieldHandle(
        name: "fullName",
        key: "9f7x5wkg",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get phone =>
      const ffai.ProjectStateFieldHandle(
        name: "phone",
        key: "jfnm6qtp",
        typeName: "String",
      );
}

abstract final class ProfilePageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_958jo4s6",
      type: "Scaffold",
      path: "ProfilePage",
      name: "ProfilePage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_dkhd560o",
            type: "AppBar",
            path: "ProfilePage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_iy9m6phh",
                  type: "Text",
                  path: "ProfilePage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Profile",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_qi2bjj60",
            type: "Container",
            path: "ProfilePage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_uhdpb924",
                type: "Column",
                path: "ProfilePage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_m2jvs82r",
                    type: "Row",
                    path: "ProfilePage.body[0].children[0].children[0]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Icon_q4zt80j3",
                        type: "Icon",
                        path: "ProfilePage.body[0].children[0].children[0].children[0]",
                        name: "Icon",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Column_aqqyijeg",
                        type: "Column",
                        path: "ProfilePage.body[0].children[0].children[0].children[1]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_dkgr372d",
                            type: "Text",
                            path: "ProfilePage.body[0].children[0].children[0].children[1].children[0]",
                            name: "Text",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_7at9himu",
                            type: "Text",
                            path: "ProfilePage.body[0].children[0].children[0].children[1].children[1]",
                            name: "Text",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Divider_x95x6nb4",
                    type: "Divider",
                    path: "ProfilePage.body[0].children[0].children[1]",
                    name: "Divider",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_hlgw5une",
                    type: "Text",
                    path: "ProfilePage.body[0].children[0].children[2]",
                    name: "Text",
                    text: "Edit details",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_xpixj4ph",
                    type: "TextField",
                    path: "ProfilePage.body[0].children[0].children[3]",
                    name: "TextField",
                    text: "Full Name",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_vcr1naxo",
                    type: "TextField",
                    path: "ProfilePage.body[0].children[0].children[4]",
                    name: "TextField",
                    text: "Phone",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_tg4d60h4",
                    type: "TextField",
                    path: "ProfilePage.body[0].children[0].children[5]",
                    name: "TextField",
                    text: "Address",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_iebnzoa6",
                    type: "Button",
                    path: "ProfilePage.body[0].children[0].children[6]",
                    name: "Button",
                    text: "Save Changes",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Divider_6pkvnakc",
                    type: "Divider",
                    path: "ProfilePage.body[0].children[0].children[7]",
                    name: "Divider",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_w71ohs9u",
                    type: "Button",
                    path: "ProfilePage.body[0].children[0].children[8]",
                    name: "Button",
                    text: "Logout",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

