// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final registerPageHandle = ffai.ProjectPageHandle<RegisterPageParams, RegisterPageState>(
  name: "RegisterPage",
  key: "Scaffold_gwqcov3f",
  route: "register",
  params: const RegisterPageParams(),
  state: const RegisterPageState(),
  widgets: RegisterPageWidgets.tree,
);

final class RegisterPageParams {
  const RegisterPageParams();
}

final class RegisterPageState {
  const RegisterPageState();
  ffai.ProjectStateFieldHandle get address =>
      const ffai.ProjectStateFieldHandle(
        name: "address",
        key: "3cdbjcpm",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get email =>
      const ffai.ProjectStateFieldHandle(
        name: "email",
        key: "v6zi8mq5",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get fullName =>
      const ffai.ProjectStateFieldHandle(
        name: "fullName",
        key: "8uvsfxdv",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get password =>
      const ffai.ProjectStateFieldHandle(
        name: "password",
        key: "6oorl5vp",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get phone =>
      const ffai.ProjectStateFieldHandle(
        name: "phone",
        key: "haj7d9xp",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get username =>
      const ffai.ProjectStateFieldHandle(
        name: "username",
        key: "s6xkszx9",
        typeName: "String",
      );
}

abstract final class RegisterPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_gwqcov3f",
      type: "Scaffold",
      path: "RegisterPage",
      name: "RegisterPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_f6bljp73",
            type: "AppBar",
            path: "RegisterPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_m6wf45oz",
                  type: "Text",
                  path: "RegisterPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Create Account",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_uzc0p3vs",
            type: "Container",
            path: "RegisterPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_eipnffxy",
                type: "Column",
                path: "RegisterPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "TextField_4tg61x4q",
                    type: "TextField",
                    path: "RegisterPage.body[0].children[0].children[0]",
                    name: "TextField",
                    text: "Username",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_jr9ch83w",
                    type: "TextField",
                    path: "RegisterPage.body[0].children[0].children[1]",
                    name: "TextField",
                    text: "Full Name",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_zmzu2dud",
                    type: "TextField",
                    path: "RegisterPage.body[0].children[0].children[2]",
                    name: "TextField",
                    text: "Email",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_zctwhg1q",
                    type: "TextField",
                    path: "RegisterPage.body[0].children[0].children[3]",
                    name: "TextField",
                    text: "Phone",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_m0wvkj02",
                    type: "TextField",
                    path: "RegisterPage.body[0].children[0].children[4]",
                    name: "TextField",
                    text: "Address",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_75capra0",
                    type: "TextField",
                    path: "RegisterPage.body[0].children[0].children[5]",
                    name: "TextField",
                    text: "Password",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_l09kwvlk",
                    type: "Button",
                    path: "RegisterPage.body[0].children[0].children[6]",
                    name: "Button",
                    text: "Register",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

