// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final shopHomePageHandle = ffai.ProjectPageHandle<ShopHomePageParams, ShopHomePageState>(
  name: "ShopHomePage",
  key: "Scaffold_dutpv5sz",
  route: "home",
  params: const ShopHomePageParams(),
  state: const ShopHomePageState(),
  widgets: ShopHomePageWidgets.tree,
);

final class ShopHomePageParams {
  const ShopHomePageParams();
}

final class ShopHomePageState {
  const ShopHomePageState();
  ffai.ProjectStateFieldHandle get banners =>
      const ffai.ProjectStateFieldHandle(
        name: "banners",
        key: "htntjmne",
        typeName: "List<DataStruct<Banner>>",
      );
  ffai.ProjectStateFieldHandle get loading =>
      const ffai.ProjectStateFieldHandle(
        name: "loading",
        key: "3g7sufza",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get products =>
      const ffai.ProjectStateFieldHandle(
        name: "products",
        key: "qcnj642u",
        typeName: "List<DataStruct<Product>>",
      );
  ffai.ProjectStateFieldHandle get searchQuery =>
      const ffai.ProjectStateFieldHandle(
        name: "searchQuery",
        key: "r94hdf4i",
        typeName: "String",
      );
}

abstract final class ShopHomePageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_dutpv5sz",
      type: "Scaffold",
      path: "ShopHomePage",
      name: "ShopHomePage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_vhzk354r",
            type: "AppBar",
            path: "ShopHomePage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_gcrhqxaa",
                  type: "Text",
                  path: "ShopHomePage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "SoleCraftPH",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_wxxwejvq",
            type: "Container",
            path: "ShopHomePage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_zxyf1y92",
                type: "Column",
                path: "ShopHomePage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_mtpnuj5j",
                    type: "Container",
                    path: "ShopHomePage.body[0].children[0].children[0]",
                    name: "Container",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "TextField_kppgtbl4",
                        type: "TextField",
                        path: "ShopHomePage.body[0].children[0].children[0].children[0]",
                        name: "searchField",
                        text: "Search shoes...",
                        triggers: const <String>[
                          "ON_TEXTFIELD_CHANGE",
                          "ON_TEXTFIELD_SUBMIT",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_9752yoc7",
                    type: "Container",
                    path: "ShopHomePage.body[0].children[0].children[1]",
                    name: "Container",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "ListView_btvgzlbb",
                        type: "ListView",
                        path: "ShopHomePage.body[0].children[0].children[1].children[0]",
                        name: "ListView",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_aq0obwea",
                            type: "Container",
                            path: "ShopHomePage.body[0].children[0].children[1].children[0].children[0]",
                            name: "Container Margin",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_vnd4q2xr",
                                type: "Container",
                                path: "ShopHomePage.body[0].children[0].children[1].children[0].children[0].children[0]",
                                name: "Container",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_h7imapbj",
                                    type: "Column",
                                    path: "ShopHomePage.body[0].children[0].children[1].children[0].children[0].children[0].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_75lyu2wa",
                                        type: "Text",
                                        path: "ShopHomePage.body[0].children[0].children[1].children[0].children[0].children[0].children[0].children[0]",
                                        name: "Text",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_v8oprm79",
                                        type: "Text",
                                        path: "ShopHomePage.body[0].children[0].children[1].children[0].children[0].children[0].children[0].children[1]",
                                        name: "Text",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Row_kkxiv48k",
                    type: "Row",
                    path: "ShopHomePage.body[0].children[0].children[2]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Button_w0j1nsgk",
                        type: "Button",
                        path: "ShopHomePage.body[0].children[0].children[2].children[0]",
                        name: "Button",
                        text: "All",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_1duuuasz",
                        type: "Button",
                        path: "ShopHomePage.body[0].children[0].children[2].children[1]",
                        name: "Button",
                        text: "Athletic",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_xtoxulev",
                        type: "Button",
                        path: "ShopHomePage.body[0].children[0].children[2].children[2]",
                        name: "Button",
                        text: "Casual",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_0aetjl6i",
                        type: "Button",
                        path: "ShopHomePage.body[0].children[0].children[2].children[3]",
                        name: "Button",
                        text: "Formal",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_jj8a7yx2",
                    type: "ProgressBar",
                    path: "ShopHomePage.body[0].children[0].children[3]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "GridView_1dacdlt7",
                    type: "GridView",
                    path: "ShopHomePage.body[0].children[0].children[4]",
                    name: "GridView",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_vrubsi6h",
                        type: "Container",
                        path: "ShopHomePage.body[0].children[0].children[4].children[0]",
                        name: "ProductCard",
                        componentName: "ProductCard",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Row_rvks3w23",
                    type: "Row",
                    path: "ShopHomePage.body[0].children[0].children[5]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "IconButton_4jqooeux",
                        type: "IconButton",
                        path: "ShopHomePage.body[0].children[0].children[5].children[0]",
                        name: "IconButton",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "IconButton_kc0hohx8",
                        type: "IconButton",
                        path: "ShopHomePage.body[0].children[0].children[5].children[1]",
                        name: "IconButton",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "IconButton_gvzyxpx1",
                        type: "IconButton",
                        path: "ShopHomePage.body[0].children[0].children[5].children[2]",
                        name: "IconButton",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "IconButton_6lm0mgr8",
                        type: "IconButton",
                        path: "ShopHomePage.body[0].children[0].children[5].children[3]",
                        name: "IconButton",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

