// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final splashPageHandle = ffai.ProjectPageHandle<SplashPageParams, SplashPageState>(
  name: "SplashPage",
  key: "Scaffold_s56wgj34",
  route: "",
  params: const SplashPageParams(),
  state: const SplashPageState(),
  widgets: SplashPageWidgets.tree,
);

final class SplashPageParams {
  const SplashPageParams();
}

final class SplashPageState {
  const SplashPageState();
}

abstract final class SplashPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_s56wgj34",
      type: "Scaffold",
      path: "SplashPage",
      name: "SplashPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_l710wj7m",
            type: "Container",
            path: "SplashPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_v3ahfbq9",
                type: "Column",
                path: "SplashPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Icon_qsq3ivmp",
                    type: "Icon",
                    path: "SplashPage.body[0].children[0].children[0]",
                    name: "Icon",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_wnfsgpfs",
                    type: "Text",
                    path: "SplashPage.body[0].children[0].children[1]",
                    name: "Text",
                    text: "SoleCraftPH",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_mn822x2p",
                    type: "Text",
                    path: "SplashPage.body[0].children[0].children[2]",
                    name: "Text",
                    text: "Footwear, Done Right",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_515vhzyz",
                    type: "Button",
                    path: "SplashPage.body[0].children[0].children[3]",
                    name: "Button",
                    text: "Get Started",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_6em5nhkw",
                    type: "Button",
                    path: "SplashPage.body[0].children[0].children[4]",
                    name: "Button",
                    text: "Browse as Guest",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

