// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final wishlistPageHandle = ffai.ProjectPageHandle<WishlistPageParams, WishlistPageState>(
  name: "WishlistPage",
  key: "Scaffold_699m3l3y",
  route: "wishlist",
  params: const WishlistPageParams(),
  state: const WishlistPageState(),
  widgets: WishlistPageWidgets.tree,
);

final class WishlistPageParams {
  const WishlistPageParams();
}

final class WishlistPageState {
  const WishlistPageState();
  ffai.ProjectStateFieldHandle get loading =>
      const ffai.ProjectStateFieldHandle(
        name: "loading",
        key: "0qpyw5py",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get wishlist =>
      const ffai.ProjectStateFieldHandle(
        name: "wishlist",
        key: "x67lk1wy",
        typeName: "List<DataStruct<Product>>",
      );
}

abstract final class WishlistPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_699m3l3y",
      type: "Scaffold",
      path: "WishlistPage",
      name: "WishlistPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_ph59ljq7",
            type: "AppBar",
            path: "WishlistPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_j0dlti57",
                  type: "Text",
                  path: "WishlistPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Wishlist",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_ygyzglxs",
            type: "Container",
            path: "WishlistPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_7nxor4ie",
                type: "Column",
                path: "WishlistPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_jxr3nf98",
                    type: "ProgressBar",
                    path: "WishlistPage.body[0].children[0].children[0]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "GridView_9b3033t4",
                    type: "GridView",
                    path: "WishlistPage.body[0].children[0].children[1]",
                    name: "GridView",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_sjrwobmd",
                        type: "Container",
                        path: "WishlistPage.body[0].children[0].children[1].children[0]",
                        name: "ProductCard",
                        componentName: "ProductCard",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

